use super::{
    AllocationMap, AllocationMapError, GLOBAL_USAGE_MAP_PAGE, GLOBAL_USAGE_MAP_RECORD_END,
    GLOBAL_USAGE_MAP_RECORD_START, GLOBAL_USAGE_MAP_ZERO_SUFFIX_SLACK, GlobalUsageMapError,
    UnsupportedGlobalUsageMap, decode_allocation_map, extended_allocation_bits,
    locate_global_usage_map_record,
};
use crate::{
    ByteCount, Error, JET3_PAGE_SIZE, PageGeometry, PageNumber, ReadLimits, ResourceBudget,
    ResourceLimitKind, ResourceLimits, classify_page,
};

type TestResult = Result<(), Box<dyn std::error::Error>>;

// FIX-0005 is generated by tools/generate_global_usage_map_fixture.py under
// the platform-independent environment recorded in docs/PROVENANCE.md.
const GLOBAL_PAGE_FIXTURE: &[u8; JET3_PAGE_SIZE.get() as usize] =
    include_bytes!("../../../fixtures/generated/global-usage-map-page1.bin");

fn budget() -> ResourceBudget {
    ResourceBudget::new(ResourceLimits::default())
}

fn budget_with_items(maximum: u64) -> ResourceBudget {
    ResourceBudget::new(ResourceLimits::new(ReadLimits::default()).with_max_item_work(maximum))
}

fn budget_with_work(maximum: u64) -> ResourceBudget {
    ResourceBudget::new(
        ResourceLimits::new(ReadLimits::default()).with_max_total_work_units(maximum),
    )
}

fn geometry(page_count: u64) -> Result<PageGeometry, Error> {
    let source_len = page_count
        .checked_mul(JET3_PAGE_SIZE.get())
        .ok_or(Error::Arithmetic {
            operation: "construct allocation test geometry",
        })?;
    PageGeometry::new(ByteCount::new(source_len), JET3_PAGE_SIZE)
}

#[test]
fn record_shape_errors_are_structured_and_charge_one_work_unit() {
    let mut resources = budget();
    assert_eq!(
        decode_allocation_map(&[], &mut resources),
        Err(AllocationMapError::EmptyRecord)
    );
    assert_eq!(resources.total_work_units(), 1);
    for actual_len in 1..5 {
        let mut resources = budget();
        assert_eq!(
            decode_allocation_map(&[0; 4][..actual_len], &mut resources),
            Err(AllocationMapError::InlineRecordTooShort { actual_len })
        );
        assert_eq!(resources.total_work_units(), 1);
    }
    let mut resources = budget();
    assert_eq!(
        decode_allocation_map(&[1, 0, 0, 0], &mut resources),
        Err(AllocationMapError::IndirectPayloadMisaligned { payload_len: 3 })
    );
    assert_eq!(resources.total_work_units(), 1);
    let mut resources = budget();
    assert_eq!(
        decode_allocation_map(&[2], &mut resources),
        Err(AllocationMapError::UnsupportedRecordType { record_type: 2 })
    );
    assert_eq!(resources.total_work_units(), 1);
}

#[test]
fn record_decode_resource_failure_charges_nothing() {
    let mut resources = budget_with_work(0);
    assert_eq!(
        decode_allocation_map(&[0, 0, 0, 0, 0], &mut resources),
        Err(AllocationMapError::Resource(Error::ResourceLimitExceeded {
            kind: ResourceLimitKind::TotalWorkUnits,
            requested: 1,
            maximum: 0,
        }))
    );
    assert_eq!(resources.item_work(), 0);
    assert_eq!(resources.total_work_units(), 0);
}

#[test]
fn inline_bits_are_lsb_first_and_charge_clear_bits() -> TestResult {
    let record = [0, 10, 0, 0, 0, 0b1000_0010];
    let mut resources = budget();
    let AllocationMap::Inline(map) = decode_allocation_map(&record, &mut resources)? else {
        return Err("expected inline map".into());
    };
    assert_eq!(map.start_page(), PageNumber::new(10));

    let mut pages = map.allocated_pages(geometry(32)?);
    assert_eq!(pages.next_page(&mut resources)?, Some(PageNumber::new(11)));
    assert_eq!(resources.item_work(), 2);
    assert_eq!(resources.total_work_units(), 3);
    assert_eq!(pages.next_page(&mut resources)?, Some(PageNumber::new(17)));
    assert_eq!(resources.item_work(), 8);
    assert_eq!(resources.total_work_units(), 9);
    assert_eq!(pages.next_page(&mut resources)?, None);
    Ok(())
}

#[test]
fn unset_inline_bits_beyond_geometry_are_not_validated() -> TestResult {
    let record = [0, 0, 0, 0, 0, 0b0000_0001, 0];
    let mut resources = budget();
    let AllocationMap::Inline(map) = decode_allocation_map(&record, &mut resources)? else {
        return Err("expected inline map".into());
    };
    let mut pages = map.allocated_pages(geometry(1)?);

    assert_eq!(pages.next_page(&mut resources)?, Some(PageNumber::new(0)));
    assert_eq!(pages.next_page(&mut resources)?, None);
    assert_eq!(resources.item_work(), 16);
    Ok(())
}

#[test]
fn set_inline_page_outside_geometry_is_rejected_and_exhausts_cursor() -> TestResult {
    let record = [0, 0, 0, 0, 0, 0b0000_0010];
    let mut resources = budget();
    let AllocationMap::Inline(map) = decode_allocation_map(&record, &mut resources)? else {
        return Err("expected inline map".into());
    };
    let mut pages = map.allocated_pages(geometry(1)?);

    assert_eq!(
        pages.next_page(&mut resources),
        Err(AllocationMapError::PageReference(Error::PageOutOfBounds {
            page: 1,
            page_count: 1,
        }))
    );
    assert_eq!(resources.item_work(), 2);
    assert_eq!(pages.next_page(&mut resources), Ok(None));
    Ok(())
}

#[test]
fn inline_resource_failure_does_not_inspect_or_advance_rejected_bit() -> TestResult {
    let record = [0, 20, 0, 0, 0, 0b0000_0100];
    let mut decode_resources = budget();
    let AllocationMap::Inline(map) = decode_allocation_map(&record, &mut decode_resources)? else {
        return Err("expected inline map".into());
    };
    let mut pages = map.allocated_pages(geometry(32)?);
    let mut constrained = budget_with_items(2);

    assert_eq!(
        pages.next_page(&mut constrained),
        Err(AllocationMapError::Resource(Error::ResourceLimitExceeded {
            kind: ResourceLimitKind::ItemWork,
            requested: 3,
            maximum: 2,
        }))
    );
    assert_eq!(constrained.item_work(), 2);
    assert_eq!(constrained.total_work_units(), 2);

    let mut replacement = budget();
    assert_eq!(
        pages.next_page(&mut replacement)?,
        Some(PageNumber::new(22))
    );
    assert_eq!(replacement.item_work(), 1);
    Ok(())
}

#[test]
fn indirect_references_preserve_zero_duplicates_and_boundaries() -> TestResult {
    let record = [
        1, 0, 0, 0, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0xff, 0xff, 0xff, 0xff,
    ];
    let mut resources = budget();
    let AllocationMap::Indirect(map) = decode_allocation_map(&record, &mut resources)? else {
        return Err("expected indirect map".into());
    };
    assert_eq!(map.reference_count(), 4);

    let mut references = map.map_page_references();
    for expected in [0, 7, 7, u32::MAX] {
        assert_eq!(references.next_reference(&mut resources)?, Some(expected));
    }
    assert_eq!(references.next_reference(&mut resources)?, None);
    assert_eq!(references.remaining_references(), 0);
    assert_eq!(resources.item_work(), 4);
    assert_eq!(resources.total_work_units(), 5);
    Ok(())
}

#[test]
fn empty_indirect_payload_is_valid_and_charges_nothing() -> TestResult {
    let mut resources = budget_with_items(0);
    let AllocationMap::Indirect(map) = decode_allocation_map(&[1], &mut resources)? else {
        return Err("expected indirect map".into());
    };
    let mut references = map.map_page_references();
    assert_eq!(references.next_reference(&mut resources)?, None);
    assert_eq!(resources.item_work(), 0);
    Ok(())
}

#[test]
fn indirect_resource_failure_preserves_the_pending_raw_reference() -> TestResult {
    let mut decode_resources = budget();
    let AllocationMap::Indirect(map) =
        decode_allocation_map(&[1, 42, 0, 0, 0], &mut decode_resources)?
    else {
        return Err("expected indirect map".into());
    };
    let mut references = map.map_page_references();
    let mut constrained = budget_with_items(0);
    assert!(matches!(
        references.next_reference(&mut constrained),
        Err(AllocationMapError::Resource(Error::ResourceLimitExceeded {
            kind: ResourceLimitKind::ItemWork,
            requested: 1,
            maximum: 0,
        }))
    ));
    assert_eq!(references.remaining_references(), 1);

    let mut replacement = budget();
    assert_eq!(references.next_reference(&mut replacement)?, Some(42));
    Ok(())
}

#[test]
fn extended_bitmap_ignores_unknown_header_bytes_and_yields_relative_indices() -> TestResult {
    let mut raw = [0; JET3_PAGE_SIZE.get() as usize];
    raw[0] = 0x05;
    raw[1..4].copy_from_slice(&[0xff, 0x7e, 0xa5]);
    raw[4] = 0b0000_0001;
    let last = raw.len() - 1;
    raw[last] = 0b1000_0000;

    let mut resources = budget();
    let page = classify_page(PageNumber::new(9), &raw, &mut resources)?;
    let mut bits = extended_allocation_bits(page)?;
    assert_eq!(bits.next_bit(&mut resources)?, Some(0));
    assert_eq!(bits.next_bit(&mut resources)?, Some(16_351));
    assert_eq!(bits.next_bit(&mut resources)?, None);
    assert_eq!(resources.item_work(), 16_352);
    assert_eq!(resources.total_work_units(), 16_353);
    Ok(())
}

#[test]
fn extended_bitmap_requires_the_classified_page_kind() -> TestResult {
    let mut raw = [0; JET3_PAGE_SIZE.get() as usize];
    raw[0] = 0x01;
    let mut resources = budget();
    let page = classify_page(PageNumber::new(1), &raw, &mut resources)?;

    assert!(matches!(
        extended_allocation_bits(page),
        Err(AllocationMapError::ExpectedExtendedUsageBitmap {
            page,
            actual: crate::PageKind::Data,
        }) if page == PageNumber::new(1)
    ));
    assert_eq!(resources.item_work(), 0);
    assert_eq!(resources.total_work_units(), 1);
    Ok(())
}

#[test]
fn extended_resource_failure_preserves_the_rejected_bit() -> TestResult {
    let mut raw = [0; JET3_PAGE_SIZE.get() as usize];
    raw[0] = 0x05;
    raw[4] = 0b0000_0010;
    let mut classification_budget = budget();
    let page = classify_page(PageNumber::new(1), &raw, &mut classification_budget)?;
    let mut bits = extended_allocation_bits(page)?;
    let mut constrained = budget_with_items(1);

    assert!(matches!(
        bits.next_bit(&mut constrained),
        Err(AllocationMapError::Resource(Error::ResourceLimitExceeded {
            kind: ResourceLimitKind::ItemWork,
            requested: 2,
            maximum: 1,
        }))
    ));
    let mut replacement = budget();
    assert_eq!(bits.next_bit(&mut replacement)?, Some(1));
    assert_eq!(replacement.item_work(), 1);
    Ok(())
}

#[test]
fn global_locator_uses_exact_record_boundaries_and_declared_slack() -> TestResult {
    let mut resources = budget();
    let page = classify_page(GLOBAL_USAGE_MAP_PAGE, GLOBAL_PAGE_FIXTURE, &mut resources)?;
    let map = locate_global_usage_map_record(page, &mut resources)?;

    assert_eq!(
        map.record_range(),
        (GLOBAL_USAGE_MAP_RECORD_START, GLOBAL_USAGE_MAP_RECORD_END)
    );
    assert_eq!(GLOBAL_USAGE_MAP_RECORD_START.get(), 1_915);
    assert_eq!(GLOBAL_USAGE_MAP_RECORD_END.get(), 2_048);
    assert_eq!(map.zero_suffix_slack(), GLOBAL_USAGE_MAP_ZERO_SUFFIX_SLACK);
    assert_eq!(map.zero_suffix_slack().get(), 92);
    assert_eq!(map.start_page(), PageNumber::new(0));
    assert_eq!(resources.total_work_units(), 95);
    assert_eq!(resources.allocation_bytes(), ByteCount::new(0));
    Ok(())
}

#[test]
fn global_inline_iteration_inverts_set_bits_and_precharges_all_pages() -> TestResult {
    let mut resources = budget();
    let page = classify_page(GLOBAL_USAGE_MAP_PAGE, GLOBAL_PAGE_FIXTURE, &mut resources)?;
    let map = locate_global_usage_map_record(page, &mut resources)?;
    let page_geometry = geometry(288)?;

    let mut allocated = map.allocated_pages(page_geometry, &mut resources)?;
    assert_eq!(resources.item_work(), 288);
    assert_eq!(allocated.next_page()?, Some(PageNumber::new(0)));
    assert_eq!(allocated.next_page()?, Some(PageNumber::new(2)));
    assert_eq!(allocated.next_page()?, Some(PageNumber::new(287)));
    assert_eq!(allocated.next_page()?, None);

    let mut unallocated = map.unallocated_pages(page_geometry, &mut resources)?;
    assert_eq!(resources.item_work(), 576);
    let mut count = 0_u64;
    while let Some(page) = unallocated.next_page()? {
        assert_ne!(page, PageNumber::new(0));
        assert_ne!(page, PageNumber::new(2));
        assert_ne!(page, PageNumber::new(287));
        count = count.checked_add(1).ok_or("test page count overflow")?;
    }
    assert_eq!(count, 285);
    assert_eq!(resources.allocation_bytes(), ByteCount::new(0));
    Ok(())
}

#[test]
fn global_locator_rejects_wrong_page_kind_and_record_layout() -> TestResult {
    let mut resources = budget();
    let page = classify_page(PageNumber::new(2), GLOBAL_PAGE_FIXTURE, &mut resources)?;
    assert_eq!(
        locate_global_usage_map_record(page, &mut resources),
        Err(GlobalUsageMapError::UnexpectedPage {
            actual: PageNumber::new(2),
        })
    );

    let mut wrong_kind = *GLOBAL_PAGE_FIXTURE;
    wrong_kind[0] = 0x02;
    let page = classify_page(GLOBAL_USAGE_MAP_PAGE, &wrong_kind, &mut resources)?;
    assert_eq!(
        locate_global_usage_map_record(page, &mut resources),
        Err(GlobalUsageMapError::UnexpectedPageKind {
            actual: crate::PageKind::TableDefinition,
        })
    );

    let mut malformed = *GLOBAL_PAGE_FIXTURE;
    malformed[GLOBAL_USAGE_MAP_RECORD_START.to_usize()?] = 0x7f;
    let page = classify_page(GLOBAL_USAGE_MAP_PAGE, &malformed, &mut resources)?;
    assert_eq!(
        locate_global_usage_map_record(page, &mut resources),
        Err(GlobalUsageMapError::Record(
            AllocationMapError::UnsupportedRecordType { record_type: 0x7f }
        ))
    );
    Ok(())
}

#[test]
fn global_locator_rejects_both_slack_boundaries() -> TestResult {
    let suffix_start = GLOBAL_USAGE_MAP_RECORD_END
        .get()
        .checked_sub(GLOBAL_USAGE_MAP_ZERO_SUFFIX_SLACK.get())
        .ok_or("test suffix arithmetic underflow")?;
    for offset in [suffix_start, GLOBAL_USAGE_MAP_RECORD_END.get() - 1] {
        let mut malformed = *GLOBAL_PAGE_FIXTURE;
        malformed[usize::try_from(offset)?] = 0;
        let mut resources = budget();
        let page = classify_page(GLOBAL_USAGE_MAP_PAGE, &malformed, &mut resources)?;
        assert_eq!(
            locate_global_usage_map_record(page, &mut resources),
            Err(GlobalUsageMapError::InvalidZeroSuffixSlack {
                offset: crate::PageOffset::new(offset),
                actual: 0,
            })
        );
    }
    Ok(())
}

#[test]
fn global_inline_phase_fails_closed_before_iteration() -> TestResult {
    let mut locate_resources = budget();
    let page = classify_page(
        GLOBAL_USAGE_MAP_PAGE,
        GLOBAL_PAGE_FIXTURE,
        &mut locate_resources,
    )?;
    let map = locate_global_usage_map_record(page, &mut locate_resources)?;

    let mut constrained = budget_with_items(287);
    assert!(matches!(
        map.allocated_pages(geometry(288)?, &mut constrained),
        Err(GlobalUsageMapError::Resource(
            Error::ResourceLimitExceeded {
                kind: ResourceLimitKind::ItemWork,
                requested: 288,
                maximum: 287,
            }
        ))
    ));
    assert_eq!(constrained.item_work(), 0);
    assert_eq!(constrained.allocation_bytes(), ByteCount::new(0));

    let mut unsupported = budget();
    assert!(matches!(
        map.unallocated_pages(geometry(1_025)?, &mut unsupported),
        Err(GlobalUsageMapError::Unsupported(
            UnsupportedGlobalUsageMap::BeyondInlineRecord {
                first_unrepresented_page,
            }
        )) if first_unrepresented_page == PageNumber::new(1_024)
    ));
    assert_eq!(unsupported.item_work(), 0);

    let mut indirect = *GLOBAL_PAGE_FIXTURE;
    indirect[GLOBAL_USAGE_MAP_RECORD_START.to_usize()?] = 0x01;
    let mut resources = budget();
    let page = classify_page(GLOBAL_USAGE_MAP_PAGE, &indirect, &mut resources)?;
    assert_eq!(
        locate_global_usage_map_record(page, &mut resources),
        Err(GlobalUsageMapError::Unsupported(
            UnsupportedGlobalUsageMap::IndirectOrExtendedLayout,
        ))
    );
    Ok(())
}
