//! Deterministic composition properties for bounded raw header access.
//!
//! These tests join candidate inspection, raw page access, and commit-region
//! snapshots without assigning semantic meaning to generated bytes. They make
//! no claim about Jet generation, encryption, database validity, or
//! compatibility.

use jet3::{
    ByteCount, COMMIT_REGION_LENGTH, COMMIT_REGION_OFFSET, CommitRegion, JET3_PAGE_SIZE,
    JetFileKind, PageNumber, RawJet3Candidate, ReadLimits, ResourceBudget, ResourceLimits,
    SliceSource, read_commit_region, read_commit_region_into,
};
use proptest::prelude::*;
use proptest::test_runner::{Config, RngSeed};

const CASES: u32 = 128;
const SEED: u64 = 0x4845_4144_4552_4333;
const PAGE_BYTES: usize = JET3_PAGE_SIZE.get() as usize;
const REGION_START: usize = COMMIT_REGION_OFFSET.get() as usize;
const REGION_BYTES: usize = COMMIT_REGION_LENGTH.get() as usize;
const REGION_END: usize = REGION_START + REGION_BYTES;

fn deterministic_config() -> Config {
    Config {
        cases: CASES,
        max_shrink_iters: 4_096,
        rng_seed: RngSeed::Fixed(SEED),
        ..Config::default()
    }
}

fn signature_case(index: u8) -> (&'static [u8; 15], JetFileKind) {
    match index % 3 {
        0 => (b"Standard Jet DB", JetFileKind::Standard),
        1 => (b"Jet System DB x", JetFileKind::System),
        _ => (b"Temp Jet DB xyz", JetFileKind::Temporary),
    }
}

fn candidate_bytes(
    page_count: usize,
    signature: &[u8; 15],
    prefix: [u8; 4],
    commit_bytes: &[u8],
) -> Vec<u8> {
    let mut bytes = vec![0_u8; page_count * PAGE_BYTES];
    bytes[..4].copy_from_slice(&prefix);
    bytes[4..19].copy_from_slice(signature);
    bytes[REGION_START..REGION_END].copy_from_slice(commit_bytes);
    bytes
}

fn operation_budget(input_len: u64, total_read: u64, page_visits: u64) -> ResourceBudget {
    ResourceBudget::new(
        ResourceLimits::new(ReadLimits::new(
            ByteCount::new(input_len),
            ByteCount::new(PAGE_BYTES as u64),
            ByteCount::new(total_read),
        ))
        .with_max_page_visits(page_visits)
        .with_max_total_work_units(page_visits),
    )
}

proptest! {
    #![proptest_config(deterministic_config())]

    #[test]
    fn candidate_and_commit_reader_preserve_generated_region_and_pair_order(
        page_count in 1_usize..=8,
        signature_index in any::<u8>(),
        prefix in any::<[u8; 4]>(),
        commit_bytes in proptest::collection::vec(any::<u8>(), REGION_BYTES),
    ) {
        let (signature, expected_kind) = signature_case(signature_index);
        let bytes = candidate_bytes(page_count, signature, prefix, &commit_bytes);
        let mut budget = operation_budget(
            bytes.len() as u64,
            15 + COMMIT_REGION_LENGTH.get(),
            0,
        );
        let source = SliceSource::new(&bytes, budget.read_budget())?;

        let candidate = RawJet3Candidate::inspect(source, &mut budget)?;
        prop_assert_eq!(candidate.signature_kind(), expected_kind);
        prop_assert_eq!(candidate.geometry().page_count(), page_count as u64);

        let mut source = candidate.into_inner();
        let region = read_commit_region(&mut source, budget.read_budget())?;

        prop_assert_eq!(region.raw_bytes().as_slice(), commit_bytes.as_slice());
        for (index, pair) in commit_bytes.chunks_exact(2).enumerate() {
            let expected = [pair[0], pair[1]];
            let observed = region
                .slot(index)
                .map(|slot| (slot.raw(), slot.classification().raw()));
            prop_assert_eq!(observed, Some((expected, expected)));
        }
        prop_assert_eq!(budget.read_budget().total_read(), ByteCount::new(527));
        prop_assert_eq!(budget.page_visits(), 0);
        prop_assert_eq!(budget.total_work_units(), 0);
    }

    #[test]
    fn candidate_page_then_commit_snapshot_share_exact_operation_accounting(
        signature_index in any::<u8>(),
        prefix in any::<[u8; 4]>(),
        commit_bytes in proptest::collection::vec(any::<u8>(), REGION_BYTES),
    ) {
        let (signature, expected_kind) = signature_case(signature_index);
        let bytes = candidate_bytes(1, signature, prefix, &commit_bytes);
        let total_read = 15 + JET3_PAGE_SIZE.get() + COMMIT_REGION_LENGTH.get();
        let mut budget = operation_budget(bytes.len() as u64, total_read, 1);
        let source = SliceSource::new(&bytes, budget.read_budget())?;
        let mut candidate = RawJet3Candidate::inspect(source, &mut budget)?;
        prop_assert_eq!(candidate.signature_kind(), expected_kind);

        let mut raw_page = [0xa5_u8; PAGE_BYTES];
        candidate.read_raw_page(PageNumber::new(0), &mut raw_page, &mut budget)?;
        let mut source = candidate.into_inner();
        let region = read_commit_region(&mut source, budget.read_budget())?;

        prop_assert_eq!(raw_page.as_slice(), bytes.as_slice());
        prop_assert_eq!(
            region.raw_bytes().as_slice(),
            &raw_page[REGION_START..REGION_END],
        );
        prop_assert_eq!(region.raw_bytes().as_slice(), commit_bytes.as_slice());
        prop_assert_eq!(budget.read_budget().total_read(), ByteCount::new(total_read));
        prop_assert_eq!(budget.page_visits(), 1);
        prop_assert_eq!(budget.total_work_units(), 1);
    }

    #[test]
    fn post_inspection_commit_limit_failure_preserves_snapshot_and_prior_work(
        available_after_inspection in 0_u64..COMMIT_REGION_LENGTH.get(),
        signature_index in any::<u8>(),
        prefix in any::<[u8; 4]>(),
        commit_bytes in proptest::collection::vec(any::<u8>(), REGION_BYTES),
        sentinel in any::<[u8; REGION_BYTES]>(),
    ) {
        let (signature, _) = signature_case(signature_index);
        let bytes = candidate_bytes(1, signature, prefix, &commit_bytes);
        let mut budget = operation_budget(
            bytes.len() as u64,
            15 + available_after_inspection,
            0,
        );
        let source = SliceSource::new(&bytes, budget.read_budget())?;
        let candidate = RawJet3Candidate::inspect(source, &mut budget)?;
        let mut source = candidate.into_inner();
        let original = CommitRegion::from_raw_bytes(sentinel);
        let mut destination = original.clone();

        let result = read_commit_region_into(
            &mut source,
            &mut destination,
            budget.read_budget(),
        );

        prop_assert!(result.is_err());
        prop_assert_eq!(destination, original);
        prop_assert_eq!(budget.read_budget().total_read(), ByteCount::new(15));
        prop_assert_eq!(budget.page_visits(), 0);
        prop_assert_eq!(budget.total_work_units(), 0);
    }
}
