//! Deterministic properties for allocation-free sequential raw page access.
//!
//! Generated bytes are synthetic and uninterpreted. These tests establish no
//! Jet generation, page type, database validity, or compatibility claim.

use jet3::{
    ByteCount, JET3_PAGE_SIZE, PageNumber, RawJet3Candidate, ReadLimits, ResourceBudget,
    ResourceLimits, SliceSource,
};
use proptest::prelude::*;
use proptest::test_runner::{Config, RngSeed};

const CASES: u32 = 128;
const SEED: u64 = 0x5241_5750_4147_4533;
const PAGE_BYTES: usize = JET3_PAGE_SIZE.get() as usize;
const SIGNATURE_BYTES: u64 = 15;

fn deterministic_config() -> Config {
    Config {
        cases: CASES,
        max_shrink_iters: 4_096,
        rng_seed: RngSeed::Fixed(SEED),
        ..Config::default()
    }
}

fn candidate_bytes(page_count: usize, fill: &[u8]) -> Vec<u8> {
    let mut bytes = vec![0_u8; page_count * PAGE_BYTES];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = fill[index % fill.len()];
    }
    bytes[4..19].copy_from_slice(b"Standard Jet DB");
    bytes
}

fn operation_budget(input_len: u64, total_read: u64, page_visits: u64) -> ResourceBudget {
    ResourceBudget::new(
        ResourceLimits::new(ReadLimits::new(
            ByteCount::new(input_len),
            JET3_PAGE_SIZE,
            ByteCount::new(total_read),
        ))
        .with_max_page_visits(page_visits)
        .with_max_total_work_units(page_visits),
    )
}

proptest! {
    #![proptest_config(deterministic_config())]

    #[test]
    fn sequential_stream_matches_every_generated_page(
        page_count in 1_usize..=16,
        fill in proptest::collection::vec(any::<u8>(), 1..=64),
    ) {
        let bytes = candidate_bytes(page_count, &fill);
        let page_read_bytes = page_count as u64 * JET3_PAGE_SIZE.get();
        let mut budget = operation_budget(
            bytes.len() as u64,
            SIGNATURE_BYTES + page_read_bytes,
            page_count as u64,
        );
        let source = SliceSource::new(&bytes, budget.read_budget())?;
        let mut candidate = RawJet3Candidate::inspect(source, &mut budget)?;
        let mut cursor = candidate.raw_pages();
        let mut observed = 0_usize;

        while let Some(page) = cursor.next_page(&mut budget)? {
            let expected_start = observed * PAGE_BYTES;
            let expected_end = expected_start + PAGE_BYTES;
            prop_assert_eq!(page.number(), PageNumber::new(observed as u64));
            prop_assert_eq!(page.bytes().as_slice(), &bytes[expected_start..expected_end]);
            observed += 1;
        }

        prop_assert_eq!(observed, page_count);
        prop_assert_eq!(cursor.pages_read(), page_count as u64);
        prop_assert_eq!(cursor.next_page_number(), None);
        prop_assert_eq!(
            budget.read_budget().total_read(),
            ByteCount::new(SIGNATURE_BYTES + page_read_bytes),
        );
        prop_assert_eq!(budget.page_visits(), page_count as u64);
        prop_assert_eq!(budget.total_work_units(), page_count as u64);
    }

    #[test]
    fn cumulative_limit_stops_at_exact_generated_page_boundary(
        page_count in 1_usize..=16,
        permitted_pages in 0_usize..16,
        fill in proptest::collection::vec(any::<u8>(), 1..=64),
    ) {
        let permitted_pages = permitted_pages.min(page_count - 1);
        let bytes = candidate_bytes(page_count, &fill);
        let permitted_read = permitted_pages as u64 * JET3_PAGE_SIZE.get();
        let mut budget = operation_budget(
            bytes.len() as u64,
            SIGNATURE_BYTES + permitted_read,
            page_count as u64,
        );
        let source = SliceSource::new(&bytes, budget.read_budget())?;
        let mut candidate = RawJet3Candidate::inspect(source, &mut budget)?;
        let mut cursor = candidate.raw_pages();

        for expected in 0..permitted_pages {
            match cursor.next_page(&mut budget)? {
                Some(page) => {
                    prop_assert_eq!(page.number(), PageNumber::new(expected as u64));
                }
                None => prop_assert!(false, "generated page must exist inside the limit"),
            }
        }

        prop_assert!(cursor.next_page(&mut budget).is_err());
        prop_assert_eq!(cursor.pages_read(), permitted_pages as u64);
        prop_assert_eq!(
            cursor.next_page_number(),
            Some(PageNumber::new(permitted_pages as u64)),
        );
        prop_assert_eq!(
            budget.read_budget().total_read(),
            ByteCount::new(SIGNATURE_BYTES + permitted_read),
        );
        prop_assert_eq!(budget.page_visits(), permitted_pages as u64);
        prop_assert_eq!(budget.total_work_units(), permitted_pages as u64);
    }
}
