param([int]$WorkerId=-1)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,((ConvertTo-Json -InputObject $v -Depth 30 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function Error-Record($record){$e=$record.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;stack=[string]$record.ScriptStackTrace}}
function Property-Metadata($td){$found=@{};$ps=$p=$null;try{$ps=$td.Properties;for($i=0;$i-lt$ps.Count;$i++){$p=$ps.Item($i);$name=[string]$p.Name;if($name-ceq'ConflictTable'-or$name-ceq'ReplicaFilter'){$found[$name]=@{ordinal=$i;type=[int]$p.Type}};Release $p;$p=$null}}finally{Release $p;Release $ps};if($found.Count-ne2){throw 'Replication properties absent or duplicate'};return $found}
function Actual-Property($td,[string]$name,$metadata){$result=[ordered]@{name=$name;ordinal=[int]$metadata.ordinal;type=[int]$metadata.type;is_null=$null;is_ps_null=$null;is_dbnull=$null;is_empty_string=$null;value=$null;elapsed_ms=0;error=$null};$ps=$p=$null;$w=[Diagnostics.Stopwatch]::StartNew();try{$ps=$td.Properties;$p=$ps.Item([int]$metadata.ordinal);if([string]$p.Name-cne$name-or[int]$p.Type-ne[int]$metadata.type){throw 'Property ordinal/name/type mismatch'};$w.Restart();$v=$p.Value;$w.Stop();$result.is_ps_null=($null-eq$v);$result.is_dbnull=[Convert]::IsDBNull($v);$result.is_empty_string=(-not$result.is_ps_null-and-not$result.is_dbnull-and$v-is[string]-and$v.Length-eq0);$result.is_null=($result.is_ps_null-or$result.is_dbnull);$result.value=if($result.is_null){$null}else{[string]$v}}catch{$result.error=Error-Record $_}finally{if($w.IsRunning){$w.Stop()};$result.elapsed_ms=[long]$w.ElapsedMilliseconds;Release $p;Release $ps};return $result}
$archivePath=Join-Path $env:JET3_WORK 'replication-property-inputs-r3.zip';$inputRoot=Join-Path $env:JET3_WORK 'replication-property-input'
if($WorkerId-lt0){
 if(Test-Path $inputRoot){Remove-Item -Recurse -Force $inputRoot};Expand-Archive -LiteralPath $archivePath -DestinationPath $inputRoot;$planPath=Join-Path $inputRoot 'plan.json';$plan=Get-Content -Raw -Encoding UTF8 -LiteralPath $planPath|ConvertFrom-Json
 if([int]$plan.worker_count-ne4){throw 'Expected four workers'};$shell=Join-Path $env:WINDIR 'SysWOW64\WindowsPowerShell\v1.0\powershell.exe';$active=@();for($i=0;$i-lt4;$i++){$p=Start-Process -FilePath $shell -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-WorkerId',$i) -PassThru;$active+=@{worker=$i;process=$p}}
 $workers=@();$failed=$false;foreach($item in $active){$item.process.WaitForExit();$code=[int]$item.process.ExitCode;$resultPath=Join-Path $env:JET3_OUTBOX "getter-worker-$($item.worker).json";$workers+=@{worker=$item.worker;exit_code=$code;result=if(Test-Path $resultPath){Identity $resultPath}else{$null}};if($code-ne0){$failed=$true};$item.process.Dispose()}
 Write-Json @{document_type='replication_property_getter_sweep_workers';archive=Identity $archivePath;plan=Identity $planPath;workers=$workers} (Join-Path $env:JET3_OUTBOX 'workers.json');if($failed){exit 1};exit 0
}
$planPath=Join-Path $inputRoot 'plan.json';$plan=Get-Content -Raw -Encoding UTF8 -LiteralPath $planPath|ConvertFrom-Json;$items=@($plan.images|Where-Object{[int]$_.worker-eq$WorkerId});$probe=New-Object -ComObject DAO.DBEngine.36
try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});$environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=32;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;ansi=[Globalization.CultureInfo]::CurrentCulture.TextInfo.ANSICodePage;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $probe}
$result=[ordered]@{document_type='replication_property_getter_sweep_worker';worker=$WorkerId;archive=Identity $archivePath;plan=Identity $planPath;environment=$environment;images=@();status='pass';error=$null};$failed=$false
foreach($item in $items){$path=Join-Path $inputRoot (Join-Path 'files' ([string]$item.file));$image=[ordered]@{group=[string]$item.group;event=[int]$item.event;role=[string]$item.role;file=[string]$item.file;expected_identity=$item.identity;before=$null;after=$null;tables=@();error=$null};$e=$db=$tds=$td=$null
 try{$image.before=Identity $path;if($image.before.sha256-cne[string]$item.identity.sha256-or[long]$image.before.size-ne[long]$item.identity.size){throw 'Input identity mismatch'};$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$tds=$db.TableDefs;foreach($tableSpec in $item.tables){$ordinal=[int]$tableSpec.ordinal;$td=$tds.Item($ordinal);if([string]$td.Name-cne[string]$tableSpec.name){throw 'Table ordinal/name mismatch'};$metadata=Property-Metadata $td;$values=@();foreach($propName in @('ConflictTable','ReplicaFilter')){$value=Actual-Property $td $propName $metadata[$propName];$values+=,$value;if($null-ne$value.error){$failed=$true}};$image.tables+=@{name=[string]$tableSpec.name;ordinal=$ordinal;properties=$values};Release $td;$td=$null}}
 catch{$image.error=Error-Record $_;$failed=$true}
 finally{Release $td;Release $tds;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;$image.after=Identity $path;if($null-ne$image.before-and$image.before.sha256-cne$image.after.sha256){$failed=$true;if($null-eq$image.error){$image.error=@{type='IdentityMismatch';message='Read-only getter changed image';hresult=0;stack=''}}}}
 $result.images+=,$image;Write-Json @{worker=$WorkerId;completed=$result.images.Count;expected=$items.Count;last_file=[string]$item.file;failed=$failed} (Join-Path $env:JET3_OUTBOX "getter-worker-$WorkerId-progress.json")
}
if($failed){$result.status='fail'};Write-Json $result (Join-Path $env:JET3_OUTBOX "getter-worker-$WorkerId.json");if($failed){exit 1}
