param([string]$CaseName='')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$Cp=[Text.Encoding]::GetEncoding(1252)
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,((ConvertTo-Json -InputObject $v -Depth 100 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function Set-Cell($rs,[string]$name,$value){$fs=$f=$null;try{$fs=$rs.Fields;$f=$fs.Item($name);$a=[object[]]::new(1);$a[0]=$value;[void]$f.GetType().InvokeMember('Value',[Reflection.BindingFlags]::SetProperty,$null,$f,$a)}finally{Release $f;Release $fs}}
function Failure($record,$engine){$numbers=@();$errors=$item=$null;try{if($null-ne$engine){$errors=$engine.Errors;for($i=0;$i-lt$errors.Count;$i++){$item=$errors.Item($i);$numbers+=[int]$item.Number;Release $item;$item=$null}}}finally{Release $item;Release $errors};$e=$record.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;numbers=@($numbers);stack=[string]$record.ScriptStackTrace}}
function Convert-Value($value,[int]$type){if($null-eq$value){return [DBNull]::Value};if($type-eq4){return [int]$value};return [string]$value}
function Add-Primary($table,[string]$name){$ix=$key=$null;try{$ix=$table.CreateIndex($name);$ix.Primary=$true;$ix.Unique=$true;$ix.Required=$true;$key=$ix.CreateField('Id');$ix.Fields.Append($key);$table.Indexes.Append($ix)}finally{Release $key;Release $ix}}
function Table-Spec($case,[string]$name){return @($case.tables|Where-Object{$_.name-eq$name})[0]}
function Create-Case([string]$path,$case,$plan){$e=$w=$db=$td=$f=$ix=$key=$rs=$rel=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$w=$e.Workspaces.Item(0);$db=$w.CreateDatabase($path,[string]$plan.database,32);foreach($table in $case.tables){$td=$db.CreateTableDef([string]$table.name);foreach($spec in $table.fields){$f=$td.CreateField([string]$spec.name,[int]$spec.type,[int]$spec.size);if([int]$spec.type-in@(10,12)){$f.AllowZeroLength=$true};$td.Fields.Append($f);Release $f;$f=$null};Add-Primary $td ("By"+[string]$table.name);$db.TableDefs.Append($td);Release $td;$td=$null;foreach($row in $table.rows){$rs=$db.OpenRecordset([string]$table.name,2);$rs.AddNew();foreach($spec in $table.fields){$name=[string]$spec.name;Set-Cell $rs $name (Convert-Value $row.$name ([int]$spec.type))};$rs.Update();$rs.Close();Release $rs;$rs=$null}};foreach($spec in $case.relations){$rel=$db.CreateRelation([string]$spec.name,[string]$spec.table,[string]$spec.foreign_table,0);$rf=$rel.CreateField([string]$spec.field);$rf.ForeignName=[string]$spec.foreign_field;$rel.Fields.Append($rf);$db.Relations.Append($rel);Release $rf;$rf=$null;Release $rel;$rel=$null}}finally{Release $rf;Release $rel;if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $key;Release $ix;Release $f;Release $td;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $w;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()}}
function Read-Properties($object){$a=@();$p=$null;try{foreach($p in $object.Properties){try{$v=$p.Value;$isNull=$null-eq$v-or[Convert]::IsDBNull($v);$item=@{name=[string]$p.Name;type=[int]$p.Type;status='ok';is_null=$isNull;value=if($isNull){$null}else{[string]$v}}}catch{$item=@{name=[string]$p.Name;type=[int]$p.Type;status='error';hresult=[int]$_.Exception.HResult;message=$_.Exception.Message}};$a+=,$item;Release $p;$p=$null}}finally{Release $p};return ,$a}
function Read-Fields($table,[bool]$full){$a=@();$fields=$field=$null;try{$fields=$table.Fields;for($i=0;$i-lt$fields.Count;$i++){$field=$fields.Item($i);$a+=@{name=[string]$field.Name;type=[int]$field.Type;size=[int]$field.Size;attributes=[int]$field.Attributes;required=[bool]$field.Required;allow_zero_length=[bool]$field.AllowZeroLength;ordinal=[int]$field.OrdinalPosition;properties=if($full){@(Read-Properties $field)}else{@()}};Release $field;$field=$null}}finally{Release $field;Release $fields};return ,$a}
function Read-Indexes($table,[bool]$full){$a=@();$indexes=$index=$fields=$field=$null;try{$indexes=$table.Indexes;for($i=0;$i-lt$indexes.Count;$i++){$index=$indexes.Item($i);$keys=@();$fields=$index.Fields;for($j=0;$j-lt$fields.Count;$j++){$field=$fields.Item($j);$keys+=@{name=[string]$field.Name;attributes=[int]$field.Attributes};Release $field;$field=$null};Release $fields;$fields=$null;$a+=@{name=[string]$index.Name;primary=[bool]$index.Primary;unique=[bool]$index.Unique;required=[bool]$index.Required;foreign=[bool]$index.Foreign;ignore_nulls=[bool]$index.IgnoreNulls;fields=@($keys);properties=if($full){@(Read-Properties $index)}else{@()}};Release $index;$index=$null}}finally{Release $field;Release $fields;Release $index;Release $indexes};return ,$a}
function Read-Row($rs,$specs){$values=[ordered]@{};$fields=$field=$null;try{$fields=$rs.Fields;foreach($spec in $specs){$name=[string]$spec.name;$field=$fields.Item($name);$v=$field.Value;if($null-eq$v-or[Convert]::IsDBNull($v)){$values[$name]=$null}elseif([int]$spec.type-eq4){$values[$name]=[int]$v}else{$values[$name]=[BitConverter]::ToString($Cp.GetBytes([string]$v)).Replace('-','').ToLowerInvariant()};Release $field;$field=$null}}finally{Release $field;Release $fields};return $values}
function Read-Table($db,$spec,[bool]$full){$td=$rs=$indexes=$index=$fields=$field=$null;try{$td=$db.TableDefs.Item([string]$spec.name);$out=@{name=[string]$spec.name;attributes=[int]$td.Attributes;fields=@(Read-Fields $td $full);indexes=@(Read-Indexes $td $full);rows=@();index_reads=@{}};$rs=$db.OpenRecordset([string]$spec.name,4);while(-not$rs.EOF){$out.rows+=,(Read-Row $rs $spec.fields);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$indexes=$td.Indexes;for($i=0;$i-lt$indexes.Count;$i++){$index=$indexes.Item($i);$indexName=[string]$index.Name;$fields=$index.Fields;$field=$fields.Item(0);$keyName=[string]$field.Name;Release $field;$field=$null;Release $fields;$fields=$null;$rs=$db.OpenRecordset([string]$spec.name,1);$rs.Index=$indexName;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};$traversal=@();while(-not$rs.EOF){$traversal+=,(Read-Row $rs $spec.fields);$rs.MoveNext()};$keys=@($out.rows|ForEach-Object{$_.$keyName}|Where-Object{$null-ne$_}|Sort-Object -Unique)+@(999999);$seek=@();foreach($k in $keys){$rs.Seek('=',[int]$k);$seek+=@{query=[int]$k;row=if($rs.NoMatch){$null}else{Read-Row $rs $spec.fields}}};$out.index_reads[$indexName]=@{field=$keyName;traversal=@($traversal);seek=@($seek)};$rs.Close();Release $rs;$rs=$null;Release $index;$index=$null};return $out}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $field;Release $fields;Release $index;Release $indexes;Release $td}}
function Capture([string]$path,$case,[string]$stage){$before=Identity $path;$e=$db=$relations=$relation=$fields=$field=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$full=$stage-eq'original';$tables=@();foreach($spec in $case.tables){$tables+=,(Read-Table $db $spec $full)};$rels=@();$relations=$db.Relations;for($i=0;$i-lt$relations.Count;$i++){$relation=$relations.Item($i);$pairs=@();$fields=$relation.Fields;for($j=0;$j-lt$fields.Count;$j++){$field=$fields.Item($j);$pairs+=@{name=[string]$field.Name;foreign_name=[string]$field.ForeignName};Release $field;$field=$null};Release $fields;$fields=$null;$rels+=@{name=[string]$relation.Name;table=[string]$relation.Table;foreign_table=[string]$relation.ForeignTable;attributes=[int]$relation.Attributes;fields=@($pairs);properties=if($full){@(Read-Properties $relation)}else{@()}};Release $relation;$relation=$null};$snapshot=@{version=[string]$db.Version;tables=@($db.TableDefs|ForEach-Object{[string]$_.Name}|Sort-Object);queries=@($db.QueryDefs|ForEach-Object{[string]$_.Name});relations=@($rels);user_tables=@($tables)}}finally{Release $field;Release $fields;Release $relation;Release $relations;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($before.sha256-ne$after.sha256){throw 'read-only capture changed file'};return @{stage=$stage;before=$before;after=$after;snapshot=$snapshot}}
function Apply-One([string]$path,$case,$op,[bool]$expectFailure){$before=Identity $path;$e=$db=$rs=$null;$error=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$false);$spec=Table-Spec $case ([string]$op.table);$rs=$db.OpenRecordset([string]$op.table,1);$rs.Index=("By"+[string]$op.table);if([string]$op.kind-eq'insert'){$rs.AddNew();foreach($field in $spec.fields){$name=[string]$field.name;Set-Cell $rs $name (Convert-Value $op.values.$name ([int]$field.type))};$rs.Update()}else{$rs.Seek('=',[int]$op.id);if($rs.NoMatch){throw 'Target row absent'};if([string]$op.kind-eq'delete'){$rs.Delete()}elseif([string]$op.kind-eq'field'){$fieldSpec=@($spec.fields|Where-Object{$_.name-eq[string]$op.column})[0];$rs.Edit();Set-Cell $rs ([string]$op.column) (Convert-Value $op.value ([int]$fieldSpec.type));$rs.Update()}else{throw 'Unknown operation'}}}catch{$error=Failure $_ $e;if(-not$expectFailure){throw}}finally{if($null-ne$rs){try{if($rs.EditMode-ne0){$rs.CancelUpdate()};$rs.Close()}catch{}};Release $rs;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($expectFailure-and$null-eq$error){throw 'Expected refusal succeeded'};return @{request=$op;before=$before;after=$after;status=if($null-eq$error){'success'}else{'rejected'};error=$error}}


Expand-Archive -LiteralPath (Join-Path $env:JET3_WORK 'inputs.zip') -DestinationPath (Join-Path $env:JET3_WORK 'input')
$root=Join-Path $env:JET3_WORK 'input';$plan=Get-Content -Raw -LiteralPath (Join-Path $root 'matrix.json')|ConvertFrom-Json
$result=@{status='pass';environment=$null;cases=@();error=$null}
try{$probe=New-Object -ComObject DAO.DBEngine.36;try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'})[0];$result.environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=[IntPtr]::Size*8;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;dll_version=$dll.FileVersionInfo.FileVersion;dll_sha256=(Identity $dll.FileName).sha256}}finally{Release $probe};foreach($case in $plan.graphs){for($rep=1;$rep-le2;$rep++){$stem="$($case.name)-r$rep";$entry=@{case=$case.name;replica=$rep;candidate=@();control_successor=$null;candidate_successor=$null;refusals=@()};foreach($stage in @('original','success-1','success-2','success-3','success-4')){$path=Join-Path $root "candidate/$stem/$stage.mdb";$cap=Capture $path $case $stage;$entry.candidate+=,$cap;Copy-Item $path (Join-Path $env:JET3_OUTBOX "$stem-$stage-candidate.mdb")};foreach($ref in $case.refusals){$path=Join-Path $root "candidate/$stem/refusal-$($ref.name).mdb";$cap=Capture $path $case "refusal-$($ref.name)";$entry.refusals+=,@{name=$ref.name;capture=$cap};Copy-Item $path (Join-Path $env:JET3_OUTBOX "$stem-refusal-$($ref.name)-candidate.mdb")};$first=$case.success[0];$table=Table-Spec $case ([string]$first.table);$old=@($table.rows|Where-Object{$_.Id-eq[int]$first.id})[0].($first.column);$reverse=[pscustomobject]@{kind='field';table=$first.table;id=$first.id;column=$first.column;value=$old};foreach($role in @('candidate','control')){$source=if($role-eq'candidate'){Join-Path $root "candidate/$stem/success-4.mdb"}else{Join-Path $root "control/$stem-success-4.mdb"};$path=Join-Path $env:JET3_WORK "$stem-successor-$role.mdb";Copy-Item $source $path;$op=Apply-One $path $case $reverse $false;$cap=Capture $path $case "successor-$role";$entry["$($role)_successor"]=@{operation=$op;capture=$cap};Copy-Item $path (Join-Path $env:JET3_OUTBOX "$stem-successor-$role.mdb")};$result.cases+=,$entry}}}catch{$result.status='fail';$result.error=Failure $_ $null}
Write-Json $result (Join-Path $env:JET3_OUTBOX 'report.json');if($result.status-ne'pass'){exit 1}
