Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$CodePage=[Text.Encoding]::GetEncoding(1252,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback))
function Identity([string]$Path){return @{size=(Get-Item -LiteralPath $Path).Length;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Release($Value){if($null-ne$Value-and[Runtime.InteropServices.Marshal]::IsComObject($Value)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($Value)}}
function Write-Json($Value,[string]$Path){[IO.File]::WriteAllText($Path,((ConvertTo-Json -InputObject $Value -Depth 60)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function To-Hex([byte[]]$Bytes){return [BitConverter]::ToString($Bytes).Replace('-','').ToLowerInvariant()}
function Hash-Bytes([byte[]]$Bytes){$sha=[Security.Cryptography.SHA256]::Create();try{return To-Hex($sha.ComputeHash($Bytes))}finally{$sha.Dispose()}}
function Failure($Record,$Engine){
 $numbers=@();$errors=$item=$null;try{if($null-ne$Engine){$errors=$Engine.Errors;for($i=0;$i-lt$errors.Count;$i++){$item=$errors.Item($i);$numbers+=[int]$item.Number;Release $item;$item=$null}}}finally{Release $item;Release $errors}
 $exception=$Record.Exception;while($null-ne$exception.InnerException){$exception=$exception.InnerException}
 return @{endpoint=$script:Endpoint;type=$exception.GetType().FullName;message=$exception.Message;hresult=[int]$exception.HResult;numbers=@($numbers);stack=[string]$Record.ScriptStackTrace}
}
function Set-Cell($Recordset,[string]$Name,$Converted){
 $fields=$field=$null;try{$fields=$Recordset.Fields;$field=$fields.Item($Name);$arguments=[object[]]::new(1);$arguments[0]=$Converted;[void]$field.GetType().InvokeMember('Value',[Reflection.BindingFlags]::SetProperty,$null,$field,$arguments)}finally{Release $field;Release $fields}
}
function Get-Cell($Fields,[string]$Name){$field=$null;try{$field=$Fields.Item($Name);return $field.Value}finally{Release $field}}
function Pattern([int]$Length,[int]$Seed){$bytes=[byte[]]::new($Length);for($i=0;$i-lt$Length;$i++){$bytes[$i]=[byte](($i*37+$Seed*13+11)%256)};return ,$bytes}
function Add-Field($Table,[string]$Name,[int]$Type,[int]$Size){$field=$null;try{$field=$Table.CreateField($Name,$Type,$Size);$Table.Fields.Append($field)}finally{Release $field}}
function Add-Primary($Table,[string]$Name,[string]$FieldName){$index=$key=$null;try{$index=$Table.CreateIndex($Name);$index.Primary=$true;$index.Unique=$true;$index.Required=$true;$key=$index.CreateField($FieldName);$index.Fields.Append($key);$Table.Indexes.Append($index)}finally{Release $key;Release $index}}
function Add-Parent($Db){$table=$null;try{$table=$Db.CreateTableDef('Parent');Add-Field $table 'Id' 4 4;Add-Field $table 'Label' 10 32;Add-Primary $table 'ByParent' 'Id';$Db.TableDefs.Append($table)}finally{Release $table}}
function Add-Child($Db){$table=$null;try{$table=$Db.CreateTableDef('Child');Add-Field $table 'Id' 4 4;Add-Field $table 'ParentId' 4 4;Add-Field $table 'Body Memo' 12 0;Add-Field $table 'Blob OLE' 11 0;Add-Primary $table 'ByChild' 'Id';$Db.TableDefs.Append($table)}finally{Release $table}}
function Add-Notes($Db,$Plan){$table=$rs=$null;try{$table=$Db.CreateTableDef('Notes Preserve');Add-Field $table 'Id' 4 4;Add-Field $table 'Body Memo' 12 0;Add-Field $table 'Blob OLE' 11 0;$Db.TableDefs.Append($table);$rs=$Db.OpenRecordset('Notes Preserve',2);$rs.AddNew();Set-Cell $rs 'Id' ([int]7);Set-Cell $rs 'Body Memo' ([string]('n'*[int]$Plan.notes.memo_length));$blob=Pattern ([int]$Plan.notes.ole_length) 0;Set-Cell $rs 'Blob OLE' ([byte[]]$blob);$rs.Update()}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $table}}
function Add-ParentRow($Db,[int]$Id,[string]$Label){$rs=$null;try{$rs=$Db.OpenRecordset('Parent',2);$rs.AddNew();Set-Cell $rs 'Id' $Id;Set-Cell $rs 'Label' $Label;$rs.Update()}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs}}
function Add-ChildRow($Db,[int]$Id,$ParentId,[string]$BodyKind,[string]$BlobKind){
 $rs=$null;try{$rs=$Db.OpenRecordset('Child',2);$rs.AddNew();Set-Cell $rs 'Id' $Id;Set-Cell $rs 'ParentId' $(if($null-eq$ParentId){[DBNull]::Value}else{[int]$ParentId})
  $body=switch($BodyKind){'null'{[DBNull]::Value}'inline'{[string]("m$Id")}'long'{[string](([char](65+($Id%20))).ToString()*4096)}'medium'{[string](([char](65+($Id%20))).ToString()*33)}default{throw 'Body kind'}};Set-Cell $rs 'Body Memo' $body
  $blob=switch($BlobKind){'null'{[DBNull]::Value}'inline'{[byte[]]@(65+($Id%20))}'long'{Pattern 4096 $Id}'medium'{Pattern 33 $Id}default{throw 'Blob kind'}};if([Convert]::IsDBNull($blob)){Set-Cell $rs 'Blob OLE' $blob}else{Set-Cell $rs 'Blob OLE' ([byte[]]$blob)};$rs.Update()
 }finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs}
}
function New-Database([string]$Path,$Plan){
 $engine=$workspace=$db=$relation=$field=$null;try{$script:Endpoint='create/database';$engine=New-Object -ComObject DAO.DBEngine.36;$workspace=$engine.Workspaces.Item(0);$db=$workspace.CreateDatabase($Path,[string]$Plan.database,32);Add-Parent $db;Add-Child $db;Add-Notes $db $Plan
  foreach($row in @(@(1,'one'),@(2,'two'),@(3,'three'),@(10,'ten'))){Add-ParentRow $db ([int]$row[0]) ([string]$row[1])}
  Add-ChildRow $db 100 1 'inline' 'long';Add-ChildRow $db 101 1 'long' 'inline';Add-ChildRow $db 102 2 'null' 'null';Add-ChildRow $db 103 $null 'inline' 'inline'
  $relation=$db.CreateRelation('ParentChild','Parent','Child',0);$field=$relation.CreateField('Id');$field.ForeignName='ParentId';$relation.Fields.Append($field);$db.Relations.Append($relation)
 }finally{Release $field;Release $relation;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $workspace;Release $engine;[GC]::Collect();[GC]::WaitForPendingFinalizers()}
}
function Field-Properties($Field){$result=New-Object Collections.ArrayList;$property=$null;try{foreach($property in $Field.Properties){$v=$property.Value;$n=$null-eq$v-or[Convert]::IsDBNull($v);[void]$result.Add(@{name=[string]$property.Name;type=[int]$property.Type;is_null=$n;value=if($n){$null}else{[string]$v}});Release $property;$property=$null}}finally{Release $property};return ,([object[]]$result.ToArray())}
function Read-Fields($Table){$result=New-Object Collections.ArrayList;$fields=$field=$null;try{$fields=$Table.Fields;for($i=0;$i-lt$fields.Count;$i++){$field=$fields.Item($i);[void]$result.Add(@{name=[string]$field.Name;type=[int]$field.Type;size=[int]$field.Size;attributes=[int]$field.Attributes;required=[bool]$field.Required;allow_zero_length=[bool]$field.AllowZeroLength;properties=Field-Properties $field});Release $field;$field=$null}}finally{Release $field;Release $fields};return ,([object[]]$result.ToArray())}
function Read-Indexes($Table){$result=New-Object Collections.ArrayList;$indexes=$index=$fields=$field=$null;try{$indexes=$Table.Indexes;for($i=0;$i-lt$indexes.Count;$i++){$index=$indexes.Item($i);$items=@();$fields=$index.Fields;for($j=0;$j-lt$fields.Count;$j++){$field=$fields.Item($j);$items+=@{name=[string]$field.Name;attributes=[int]$field.Attributes};Release $field;$field=$null};Release $fields;$fields=$null;[void]$result.Add(@{name=[string]$index.Name;primary=[bool]$index.Primary;unique=[bool]$index.Unique;required=[bool]$index.Required;foreign=[bool]$index.Foreign;ignore_nulls=[bool]$index.IgnoreNulls;fields=@($items)});Release $index;$index=$null}}finally{Release $field;Release $fields;Release $index;Release $indexes};return ,([object[]]$result.ToArray())}
function Read-Row($Rs,[string]$Name){
 $fields=$field=$null;try{$fields=$Rs.Fields;if($Name-eq'Parent'){$id=[int](Get-Cell $fields 'Id');$label=[string](Get-Cell $fields 'Label');return @{id=$id;label_hex=To-Hex($CodePage.GetBytes($label))}}
  $id=[int](Get-Cell $fields 'Id');$p=Get-Cell $fields 'ParentId';$parent=if($null-eq$p-or[Convert]::IsDBNull($p)){$null}else{[int]$p};$body=Get-Cell $fields 'Body Memo';$bodyNull=$null-eq$body-or[Convert]::IsDBNull($body);$blob=Get-Cell $fields 'Blob OLE';$blobNull=$null-eq$blob-or[Convert]::IsDBNull($blob);return @{id=$id;parent_id=$parent;body_hex=if($bodyNull){$null}else{To-Hex($CodePage.GetBytes([string]$body))};blob_hex=if($blobNull){$null}else{To-Hex([byte[]]$blob)}}
 }finally{Release $field;Release $fields}
}
function Read-Table($Db,[string]$Name){
 $table=$rs=$indexes=$index=$null;try{$table=$Db.TableDefs.Item($Name);$snapshot=@{name=$Name;attributes=[int]$table.Attributes;fields=Read-Fields $table;indexes=Read-Indexes $table;rows=@();index_reads=@{}};$rs=$Db.OpenRecordset($Name,4);while(-not$rs.EOF){$snapshot.rows+=,(Read-Row $rs $Name);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$indexes=$table.Indexes;for($i=0;$i-lt$indexes.Count;$i++){$index=$indexes.Item($i);$rs=$Db.OpenRecordset($Name,1);$rs.Index=[string]$index.Name;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};$traversal=@();while(-not$rs.EOF){$traversal+=,(Read-Row $rs $Name);$rs.MoveNext()};$queries=@(if($Name-eq'Parent'-or[string]$index.Name-eq'ByChild'){$snapshot.rows|ForEach-Object{$_.id}}else{$snapshot.rows|Where-Object{$null-ne$_.parent_id}|ForEach-Object{$_.parent_id}})+@(-1,999,999999);$queries=@($queries|Sort-Object -Unique);$seeks=@();foreach($q in $queries){$rs.Seek('=',[int]$q);$seeks+=@{query=$q;row=if($rs.NoMatch){$null}else{Read-Row $rs $Name}}};$snapshot.index_reads[[string]$index.Name]=@{traversal=@($traversal);seek=@($seeks)};$rs.Close();Release $rs;$rs=$null;Release $index;$index=$null};return $snapshot
 }finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $index;Release $indexes;Release $table}
}
function Read-Notes($Db){$rs=$fields=$null;try{$rs=$Db.OpenRecordset('Notes Preserve',4);$fields=$rs.Fields;$body=[string](Get-Cell $fields 'Body Memo');$blob=[byte[]](Get-Cell $fields 'Blob OLE');return @{id=[int](Get-Cell $fields 'Id');body_length=$CodePage.GetByteCount($body);body_sha256=Hash-Bytes($CodePage.GetBytes($body));blob_length=$blob.Length;blob_sha256=Hash-Bytes $blob}}finally{Release $fields;if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs}}
function Capture([string]$Path,[string]$Stage){
  $before=Identity $Path;$engine=$db=$relationsObject=$relation=$relationFields=$field=$null;$status='pass';$errorDetail=$null;$snapshot=@{};try{$script:Endpoint="capture/$Stage";$engine=New-Object -ComObject DAO.DBEngine.36;$db=$engine.OpenDatabase($Path,$false,$true);$relations=@();$relationsObject=$db.Relations;for($i=0;$i-lt$relationsObject.Count;$i++){$relation=$relationsObject.Item($i);$rf=@();$relationFields=$relation.Fields;for($j=0;$j-lt$relationFields.Count;$j++){$field=$relationFields.Item($j);$rf+=@{name=[string]$field.Name;foreign_name=[string]$field.ForeignName};Release $field;$field=$null};Release $relationFields;$relationFields=$null;$relations+=@{name=[string]$relation.Name;table=[string]$relation.Table;foreign_table=[string]$relation.ForeignTable;attributes=[int]$relation.Attributes;fields=@($rf)};Release $relation;$relation=$null};Release $relationsObject;$relationsObject=$null;$snapshot=@{version=[string]$db.Version;tables=@($db.TableDefs|ForEach-Object{[string]$_.Name}|Sort-Object);queries=@($db.QueryDefs|ForEach-Object{[string]$_.Name});relations=@($relations);parent=Read-Table $db 'Parent';child=Read-Table $db 'Child';notes=Read-Notes $db}}catch{$status='error';$errorDetail=Failure $_ $engine}finally{Release $field;Release $relationFields;Release $relation;Release $relationsObject;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $engine;[GC]::Collect();[GC]::WaitForPendingFinalizers()};return @{stage=$Stage;status=$status;error=$errorDetail;before=$before;after=Identity $Path;snapshot=$snapshot}
}
