param([string]$CaseName='')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$Cp=[Text.Encoding]::GetEncoding(1252,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback))
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Hex([byte[]]$b){[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,((ConvertTo-Json -InputObject $v -Depth 100 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function Set-Cell($rs,[string]$name,$value){$fs=$f=$null;try{$fs=$rs.Fields;$f=$fs.Item($name);$a=[object[]]::new(1);$a[0]=$value;[void]$f.GetType().InvokeMember('Value',[Reflection.BindingFlags]::SetProperty,$null,$f,$a)}finally{Release $f;Release $fs}}
function Pattern([int]$length,[int]$seed){$b=[byte[]]::new($length);for($i=0;$i-lt$length;$i++){$b[$i]=[byte](($i*37+$seed*13+11)%256)};return ,$b}
function Materialize($recipe,[int]$type){if($null-eq$recipe){return [DBNull]::Value};if($recipe-isnot[Management.Automation.PSCustomObject]){if($type-eq4){return [int]$recipe};return [string]$recipe};$kind=[string]$recipe.kind;if($kind-eq'repeat'){$n=[int]$recipe.length;$byte=[byte][int]$recipe.byte;if($type-eq11){$b=[byte[]]::new($n);for($i=0;$i-lt$n;$i++){$b[$i]=$byte};return ,$b};return [string](([char]$byte).ToString()*$n)};if($kind-eq'pattern'){return ,(Pattern ([int]$recipe.length) ([int]$recipe.seed))};throw "Unknown payload kind $kind"}
function Add-Primary($table,[string]$name){$ix=$key=$null;try{$ix=$table.CreateIndex($name);$ix.Primary=$true;$ix.Unique=$true;$ix.Required=$true;$key=$ix.CreateField('Id');$ix.Fields.Append($key);$table.Indexes.Append($ix)}finally{Release $key;Release $ix}}
function Create-Case([string]$path,$case,$plan){$e=$w=$db=$td=$f=$rs=$rel=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$w=$e.Workspaces.Item(0);$db=$w.CreateDatabase($path,[string]$plan.database,32);foreach($table in $case.tables){$td=$db.CreateTableDef([string]$table.name);foreach($spec in $table.fields){$f=$td.CreateField([string]$spec.name,[int]$spec.type,[int]$spec.size);if([int]$spec.attributes-ne0){$f.Attributes=[int]$spec.attributes};if([int]$spec.type-in@(10,12)){$f.AllowZeroLength=[bool]$spec.allow_zero_length};$td.Fields.Append($f);Release $f;$f=$null};Add-Primary $td ("By"+[string]$table.name);$db.TableDefs.Append($td);Release $td;$td=$null;foreach($row in $table.rows){$rs=$db.OpenRecordset([string]$table.name,2);$rs.AddNew();foreach($spec in $table.fields){$v=Materialize $row.([string]$spec.name) ([int]$spec.type);if([int]$spec.type-eq11-and-not[Convert]::IsDBNull($v)){$v=[byte[]]$v};Set-Cell $rs ([string]$spec.name) $v};$rs.Update();$rs.Close();Release $rs;$rs=$null}};foreach($spec in $case.relations){$rel=$db.CreateRelation([string]$spec.name,[string]$spec.table,[string]$spec.foreign_table,0);$rf=$rel.CreateField([string]$spec.field);$rf.ForeignName=[string]$spec.foreign_field;$rel.Fields.Append($rf);$db.Relations.Append($rel);Release $rf;$rf=$null;Release $rel;$rel=$null}}finally{Release $rf;Release $rel;if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $f;Release $td;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $w;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()}}
function Read-Properties($object){$a=@();$p=$null;try{foreach($p in $object.Properties){try{$v=$p.Value;$isNull=$null-eq$v-or[Convert]::IsDBNull($v);$item=@{name=[string]$p.Name;type=[int]$p.Type;status='ok';is_null=$isNull;value=if($isNull){$null}else{[string]$v}}}catch{$item=@{name=[string]$p.Name;type=[int]$p.Type;status='error';hresult=[int]$_.Exception.HResult;message=$_.Exception.Message}};$a+=,$item;Release $p;$p=$null}}finally{Release $p};return ,$a}
function Read-Fields($table,[bool]$full){$a=@();$fs=$f=$null;try{$fs=$table.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$a+=@{name=[string]$f.Name;type=[int]$f.Type;size=[int]$f.Size;attributes=[int]$f.Attributes;required=[bool]$f.Required;allow_zero_length=[bool]$f.AllowZeroLength;ordinal=[int]$f.OrdinalPosition;properties=if($full){@(Read-Properties $f)}else{@()}};Release $f;$f=$null}}finally{Release $f;Release $fs};return ,$a}
function Read-Indexes($table,[bool]$full){$a=@();$xs=$x=$fs=$f=$null;try{$xs=$table.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$keys=@();$fs=$x.Fields;for($j=0;$j-lt$fs.Count;$j++){$f=$fs.Item($j);$keys+=@{name=[string]$f.Name;attributes=[int]$f.Attributes};Release $f;$f=$null};Release $fs;$fs=$null;$a+=@{name=[string]$x.Name;primary=[bool]$x.Primary;unique=[bool]$x.Unique;required=[bool]$x.Required;foreign=[bool]$x.Foreign;ignore_nulls=[bool]$x.IgnoreNulls;fields=@($keys);properties=if($full){@(Read-Properties $x)}else{@()}};Release $x;$x=$null}}finally{Release $f;Release $fs;Release $x;Release $xs};return ,$a}
function Read-Row($rs,$specs){$v=[ordered]@{};$fs=$f=$null;try{$fs=$rs.Fields;foreach($s in $specs){$name=[string]$s.name;$f=$fs.Item($name);$x=$f.Value;if($null-eq$x-or[Convert]::IsDBNull($x)){$v[$name]=$null}elseif([int]$s.type-eq4){$v[$name]=[int]$x}elseif([int]$s.type-eq11){$v[$name]=Hex([byte[]]$x)}else{$v[$name]=Hex($Cp.GetBytes([string]$x))};Release $f;$f=$null}}finally{Release $f;Release $fs};return $v}
function Read-Table($db,$spec,[bool]$full){$td=$rs=$xs=$x=$fs=$f=$null;try{$td=$db.TableDefs.Item([string]$spec.name);$out=@{name=[string]$spec.name;attributes=[int]$td.Attributes;properties=if($full){@(Read-Properties $td)}else{@()};fields=@(Read-Fields $td $full);indexes=@(Read-Indexes $td $full);rows=@();index_reads=@{}};$rs=$db.OpenRecordset([string]$spec.name,4);while(-not$rs.EOF){$out.rows+=,(Read-Row $rs $spec.fields);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$xs=$td.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$ix=[string]$x.Name;$fs=$x.Fields;$f=$fs.Item(0);$keyName=[string]$f.Name;Release $f;$f=$null;Release $fs;$fs=$null;$rs=$db.OpenRecordset([string]$spec.name,1);$rs.Index=$ix;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};$tr=@();while(-not$rs.EOF){$tr+=,(Read-Row $rs $spec.fields);$rs.MoveNext()};$keys=@($out.rows|ForEach-Object{$_.$keyName}|Where-Object{$null-ne$_}|ForEach-Object{[int]$_}|Sort-Object -Unique)+@(999999);$seek=@();foreach($key in $keys){$rs.Seek('=',[int]$key);$seek+=@{query=[int]$key;row=if($rs.NoMatch){$null}else{Read-Row $rs $spec.fields}}};$out.index_reads[$ix]=@{field=$keyName;traversal=@($tr);seek=@($seek)};$rs.Close();Release $rs;$rs=$null;Release $x;$x=$null};return $out}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $f;Release $fs;Release $x;Release $xs;Release $td}}
function Capture([string]$path,$case,[string]$stage){$before=Identity $path;$e=$db=$rels=$r=$rfs=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$tables=@();foreach($spec in $case.tables){$tables+=,(Read-Table $db $spec ($stage-eq'original'))};$ra=@();$rels=$db.Relations;for($i=0;$i-lt$rels.Count;$i++){$r=$rels.Item($i);$pairs=@();$rfs=$r.Fields;for($j=0;$j-lt$rfs.Count;$j++){$rf=$rfs.Item($j);$pairs+=@{name=[string]$rf.Name;foreign_name=[string]$rf.ForeignName};Release $rf;$rf=$null};Release $rfs;$rfs=$null;$ra+=@{name=[string]$r.Name;table=[string]$r.Table;foreign_table=[string]$r.ForeignTable;attributes=[int]$r.Attributes;fields=@($pairs);properties=if($stage-eq'original'){@(Read-Properties $r)}else{@()}};Release $r;$r=$null};$snap=@{version=[string]$db.Version;tables=@($db.TableDefs|ForEach-Object{[string]$_.Name}|Sort-Object);queries=@($db.QueryDefs|ForEach-Object{[string]$_.Name});relations=@($ra);user_tables=@($tables)}}finally{Release $rf;Release $rfs;Release $r;Release $rels;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($before.sha256-ne$after.sha256){throw 'Read-only capture changed file'};return @{stage=$stage;before=$before;after=$after;snapshot=$snap}}
function Table-Spec($case,[string]$name){return @($case.tables|Where-Object{$_.name-eq$name})[0]}
function Failure($record,$engine){$numbers=@();$errors=$item=$null;try{if($null-ne$engine){$errors=$engine.Errors;for($i=0;$i-lt$errors.Count;$i++){$item=$errors.Item($i);$numbers+=[int]$item.Number;Release $item;$item=$null}}}finally{Release $item;Release $errors};$e=$record.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;numbers=@($numbers);stack=[string]$record.ScriptStackTrace}}
function Apply-One([string]$path,$case,$op,[bool]$expectFailure){$before=Identity $path;$e=$db=$rs=$null;$error=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$false);$spec=Table-Spec $case ([string]$op.table);$rs=$db.OpenRecordset([string]$op.table,1);$rs.Index=("By"+[string]$op.table);if([string]$op.kind-eq'insert'){$rs.AddNew();foreach($field in $spec.fields){$name=[string]$field.name;$raw=$op.values.$name;if([int]$field.attributes-eq16-and$null-eq$raw){continue};$value=Materialize $raw ([int]$field.type);if([int]$field.type-eq11-and-not[Convert]::IsDBNull($value)){$value=[byte[]]$value};Set-Cell $rs $name $value};$rs.Update()}else{$rs.Seek('=',[int]$op.id);if($rs.NoMatch){throw 'Target row absent'};if([string]$op.kind-eq'delete'){$rs.Delete()}elseif([string]$op.kind-eq'field'){$field=@($spec.fields|Where-Object{$_.name-eq[string]$op.column})[0];$rs.Edit();Set-Cell $rs ([string]$op.column) (Materialize $op.value ([int]$field.type));$rs.Update()}elseif([string]$op.kind-eq'replace'){$rs.Edit();foreach($field in $spec.fields){$name=[string]$field.name;$raw=$op.values.$name;if([int]$field.attributes-eq16-and$null-eq$raw){continue};$value=Materialize $raw ([int]$field.type);if([int]$field.type-eq11-and-not[Convert]::IsDBNull($value)){$value=[byte[]]$value};Set-Cell $rs $name $value};$rs.Update()}else{throw 'Unknown operation'}}}catch{$error=Failure $_ $e;if(-not$expectFailure){throw}}finally{if($null-ne$rs){try{if($rs.EditMode-ne0){$rs.CancelUpdate()};$rs.Close()}catch{}};Release $rs;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($expectFailure-and$null-eq$error){throw 'Expected refusal succeeded'};return @{request=$op;before=$before;after=$after;status=if($null-eq$error){'success'}else{'rejected'};error=$error}}
$zip=Join-Path $env:JET3_WORK 'inputs.zip';$root=Join-Path $env:JET3_WORK 'input';if(-not(Test-Path $root)){Expand-Archive -LiteralPath $zip -DestinationPath $root};$plan=Get-Content -Raw -LiteralPath (Join-Path $root 'matrix.json')|ConvertFrom-Json
if($CaseName-eq''){$fail=@();$running=@();foreach($case in $plan.graphs){for($rep=1;$rep-le[int]$plan.replicas;$rep++){$name="$($case.name)-r$rep";$exe="$env:SystemRoot\SysWOW64\WindowsPowerShell\v1.0\powershell.exe";$p=Start-Process -FilePath $exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-CaseName',$name) -PassThru;$running+=,[pscustomobject]@{name=$name;process=$p};if($running.Count-eq6){foreach($job in $running){$job.process.WaitForExit();if($job.process.ExitCode-ne0){$fail+=$job.name}};$running=@()}}};foreach($job in $running){$job.process.WaitForExit();if($job.process.ExitCode-ne0){$fail+=$job.name}};if($fail.Count){throw ('Workers failed: '+($fail-join','))};exit 0}
$match=[regex]::Match($CaseName,'^(.*)-r([0-9]+)$');if(-not$match.Success){throw 'Invalid worker case name'};$graphName=$match.Groups[1].Value;$rep=[int]$match.Groups[2].Value;$case=@($plan.graphs|Where-Object{$_.name-eq$graphName})[0];$native=Join-Path $env:JET3_WORK "$CaseName-native.mdb";$result=[ordered]@{case=$graphName;replica=$rep;source_revision=[string]$plan.source_revision;matrix_sha256=(Identity (Join-Path $root 'matrix.json')).sha256;environment=$null;status='fail';error=$null;roles=@()}
try{$probe=New-Object -ComObject DAO.DBEngine.36;try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});if($dll.Count-ne1){throw 'DAO DLL absent'};$result.environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=[IntPtr]::Size*8;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $probe};Create-Case $native $case $plan;foreach($role in @('candidate','control')){$source=if($role-eq'candidate'){Join-Path $root "candidates/$CaseName.mdb"}else{$native};$work=Join-Path $env:JET3_WORK "$CaseName-$role-work.mdb";Copy-Item $source $work;$entry=@{role=$role;stages=@();refusals=@()};$paths=@{};foreach($stage in $case.lifecycle.stages){$operations=@();foreach($op in $stage.operations){$operations+=,(Apply-One $work $case $op $false)};$capture=Capture $work $case ([string]$stage.name);$checkpoint=Join-Path $env:JET3_WORK "$CaseName-$role-$($stage.name).mdb";Copy-Item $work $checkpoint;$paths[[string]$stage.name]=$checkpoint;Copy-Item $work (Join-Path $env:JET3_OUTBOX "$CaseName-$role-$($stage.name).mdb");$entry.stages+=,@{name=[string]$stage.name;operations=@($operations);capture=$capture}};foreach($ref in $case.lifecycle.refusals){$base=$paths[[string]$ref.source_stage];$refpath=Join-Path $env:JET3_WORK "$CaseName-$role-refusal-$($ref.name).mdb";Copy-Item $base $refpath;$operation=Apply-One $refpath $case $ref.operation $true;$capture=Capture $refpath $case ("refusal-"+[string]$ref.name);Copy-Item $refpath (Join-Path $env:JET3_OUTBOX "$CaseName-$role-refusal-$($ref.name).mdb");$entry.refusals+=,@{name=[string]$ref.name;source_stage=[string]$ref.source_stage;expected=[int]$ref.number;operation=$operation;capture=$capture}};$result.roles+=,$entry};$result.status='pass'}catch{$result.error=@{type=$_.Exception.GetType().FullName;message=$_.Exception.Message;hresult=[int]$_.Exception.HResult;stack=[string]$_.ScriptStackTrace}}
Write-Json $result (Join-Path $env:JET3_OUTBOX "$CaseName.json");if($result.status-ne'pass'){exit 1}
