param([string]$CaseName='')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$Cp=[Text.Encoding]::GetEncoding(1252,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback))
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Hex([byte[]]$b){[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,(ConvertTo-Json -InputObject $v -Depth 100 -Compress),(New-Object Text.UTF8Encoding($false)))}
function Set-Cell($rs,[string]$name,$value){$fs=$f=$null;try{$fs=$rs.Fields;$f=$fs.Item($name);$a=[object[]]::new(1);$a[0]=$value;[void]$f.GetType().InvokeMember('Value',[Reflection.BindingFlags]::SetProperty,$null,$f,$a)}finally{Release $f;Release $fs}}
function Get-Cell($fs,[string]$name){$f=$null;try{$f=$fs.Item($name);return $f.Value}finally{Release $f}}
function Pattern([int]$length,[int]$seed){$b=[byte[]]::new($length);for($i=0;$i-lt$length;$i++){$b[$i]=[byte](($i*37+$seed*13+11)%256)};return ,$b}
function Materialize($recipe,[string]$field,[int]$row,[int]$column){
 if($null-eq$recipe){return [DBNull]::Value};if($recipe -isnot [Management.Automation.PSCustomObject]){return $recipe};$kind=[string]$recipe.kind
 switch($kind){'null'{return [DBNull]::Value};'empty'{if($field-like'*OLE'-or$field-eq'Blob'){return ,([byte[]]::new(0))};return [string]''};'repeat'{if($field-like'*OLE'-or$field-eq'Blob'){$b=[byte[]]::new([int]$recipe.length);for($i=0;$i-lt$b.Length;$i++){$b[$i]=[byte][int]$recipe.byte};return ,$b};return [string](([char][int]$recipe.byte).ToString()*[int]$recipe.length)};'pattern'{return ,(Pattern ([int]$recipe.length) ([int]$recipe.seed))};'ascii'{if($field-eq'Label'){return "label-$row"};return ('r{0:d2}-c{1:d2}'-f$row,$column)};default{throw "Unknown value kind $kind"}}
}
function Add-Primary($table,[string]$name,[string]$fieldName){$ix=$key=$null;try{$ix=$table.CreateIndex($name);$ix.Primary=$true;$ix.Unique=$true;$ix.Required=$true;$key=$ix.CreateField($fieldName);$ix.Fields.Append($key);$table.Indexes.Append($ix)}finally{Release $key;Release $ix}}
function Add-Field($table,$spec){$f=$null;try{$f=$table.CreateField([string]$spec.name,[int]$spec.type,[int]$spec.size);if([int]$spec.attributes-ne0){$f.Attributes=[int]$spec.attributes};if([int]$spec.type-in@(10,12)){$f.AllowZeroLength=[bool]$spec.allow_zero_length};$table.Fields.Append($f)}finally{Release $f}}
function Insert-Row($db,[string]$table,$specs,$values,[int]$row){$rs=$null;try{$rs=$db.OpenRecordset($table,2);$rs.AddNew();for($i=0;$i-lt$specs.Count;$i++){$s=$specs[$i];$name=[string]$s.name;$v=$values.$name;if($name-eq'Id'-and$null-eq$v){continue};$converted=Materialize $v $name $row $i;if([int]$s.type-eq11-and-not[Convert]::IsDBNull($converted)){$converted=[byte[]]$converted};Set-Cell $rs $name $converted};$rs.Update()}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs}}
function Create-Case([string]$path,$case,$plan){
 $e=$w=$db=$t=$r=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$w=$e.Workspaces.Item(0);$db=$w.CreateDatabase($path,[string]$plan.database,32)
  $t=$db.CreateTableDef('Parent');$pf=@([pscustomobject]@{name='Id';type=4;size=4;attributes=0;allow_zero_length=$false},[pscustomobject]@{name='Label';type=10;size=32;attributes=0;allow_zero_length=$false});foreach($s in $pf){Add-Field $t $s};Add-Primary $t 'ByParent' 'Id';$db.TableDefs.Append($t);Release $t;$t=$null
  foreach($p in $case.parents){$vals=[pscustomobject]@{Id=[int]$p.Id;Label=[string]$p.Label};Insert-Row $db 'Parent' $pf $vals ([int]$p.Id)}
  $t=$db.CreateTableDef('Child');foreach($s in $case.fields){Add-Field $t $s};Add-Primary $t 'ByChild' 'Id';$db.TableDefs.Append($t);Release $t;$t=$null
  for($i=0;$i-lt$case.rows.Count;$i++){Insert-Row $db 'Child' $case.fields $case.rows[$i] $i}
  $r=$db.CreateRelation([string]$case.relation.name,'Parent','Child',0);$rf=$r.CreateField('Id');$rf.ForeignName='ParentId';$r.Fields.Append($rf);$db.Relations.Append($r)
 }finally{Release $rf;Release $r;Release $t;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $w;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()}
}
function Read-Properties($field){$a=@();$p=$null;try{foreach($p in $field.Properties){$v=$p.Value;$nullv=$null-eq$v-or[Convert]::IsDBNull($v);$a+=@{name=[string]$p.Name;type=[int]$p.Type;is_null=$nullv;value=if($nullv){$null}else{[string]$v}};Release $p;$p=$null}}finally{Release $p};return ,$a}
function Read-Fields($table){$a=@();$fs=$f=$null;try{$fs=$table.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$a+=@{name=[string]$f.Name;type=[int]$f.Type;size=[int]$f.Size;attributes=[int]$f.Attributes;required=[bool]$f.Required;allow_zero_length=[bool]$f.AllowZeroLength;properties=Read-Properties $f};Release $f;$f=$null}}finally{Release $f;Release $fs};return ,$a}
function Read-Indexes($table){$a=@();$xs=$x=$fs=$f=$null;try{$xs=$table.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$keys=@();$fs=$x.Fields;for($j=0;$j-lt$fs.Count;$j++){$f=$fs.Item($j);$keys+=@{name=[string]$f.Name;attributes=[int]$f.Attributes};Release $f;$f=$null};Release $fs;$fs=$null;$a+=@{name=[string]$x.Name;primary=[bool]$x.Primary;unique=[bool]$x.Unique;required=[bool]$x.Required;foreign=[bool]$x.Foreign;ignore_nulls=[bool]$x.IgnoreNulls;fields=@($keys)};Release $x;$x=$null}}finally{Release $f;Release $fs;Release $x;Release $xs};return ,$a}
function Read-Row($rs,$specs){$fs=$f=$null;$v=[ordered]@{};try{$fs=$rs.Fields;foreach($s in $specs){$name=[string]$s.name;$f=$fs.Item($name);$x=$f.Value;if($null-eq$x-or[Convert]::IsDBNull($x)){$v[$name]=$null}elseif([int]$s.type-eq4){$v[$name]=[int]$x}elseif([int]$s.type-eq11){$v[$name]=Hex([byte[]]$x)}else{$v[$name]=Hex($Cp.GetBytes([string]$x))};Release $f;$f=$null}}finally{Release $f;Release $fs};return $v}
function Read-Table($db,[string]$name,$specs){$td=$rs=$xs=$x=$null;try{$td=$db.TableDefs.Item($name);$out=@{name=$name;attributes=[int]$td.Attributes;fields=(Read-Fields $td);indexes=(Read-Indexes $td);rows=@();index_reads=@{}};$rs=$db.OpenRecordset($name,4);while(-not$rs.EOF){$out.rows+=,(Read-Row $rs $specs);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$xs=$td.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$ix=[string]$x.Name;$rs=$db.OpenRecordset($name,1);$rs.Index=$ix;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};$tr=@();while(-not$rs.EOF){$tr+=,(Read-Row $rs $specs);$rs.MoveNext()};$keys=if($name-eq'Parent'){@(1,2,3,999)}elseif($ix-eq'ByChild'){@($out.rows|ForEach-Object{[int]$_.Id})+@(999)}else{@(1,2,3,999)};$seeks=@();foreach($key in $keys){$rs.Seek('=',[int]$key);$seeks+=@{query=[int]$key;row=if($rs.NoMatch){$null}else{Read-Row $rs $specs}}};$out.index_reads[$ix]=@{traversal=@($tr);seek=@($seeks)};$rs.Close();Release $rs;$rs=$null;Release $x;$x=$null};return $out}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $x;Release $xs;Release $td}}
function Capture([string]$path,$case){$before=Identity $path;$e=$db=$rels=$r=$rfs=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$pf=@([pscustomobject]@{name='Id';type=4},[pscustomobject]@{name='Label';type=10});$ra=@();$rels=$db.Relations;for($i=0;$i-lt$rels.Count;$i++){$r=$rels.Item($i);$fa=@();$rfs=$r.Fields;for($j=0;$j-lt$rfs.Count;$j++){$rf=$rfs.Item($j);$fa+=@{name=[string]$rf.Name;foreign_name=[string]$rf.ForeignName};Release $rf;$rf=$null};Release $rfs;$rfs=$null;$ra+=@{name=[string]$r.Name;table=[string]$r.Table;foreign_table=[string]$r.ForeignTable;attributes=[int]$r.Attributes;fields=@($fa)};Release $r;$r=$null};$snap=@{version=[string]$db.Version;tables=@($db.TableDefs|ForEach-Object{[string]$_.Name}|Sort-Object);relations=@($ra);parent=Read-Table $db 'Parent' $pf;child=Read-Table $db 'Child' $case.fields}}finally{Release $rf;Release $rfs;Release $r;Release $rels;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};return @{before=$before;after=Identity $path;snapshot=$snap}}
$plan=Get-Content -Raw -LiteralPath (Join-Path $env:JET3_WORK 'matrix.json')|ConvertFrom-Json
if($CaseName-eq''){$fail=@();foreach($case in $plan.arms){for($rep=1;$rep-le[int]$plan.replicas;$rep++){$name="$($case.name)-r$rep";$exe="$env:SystemRoot\SysWOW64\WindowsPowerShell\v1.0\powershell.exe";$p=Start-Process -FilePath $exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-CaseName',$name) -Wait -PassThru;if($p.ExitCode-ne0){$fail+=$name}}};if($fail.Count){throw ('Workers failed: '+($fail-join','))};exit 0}
$parts=$CaseName-split'-r';$arm=$parts[0];$rep=[int]$parts[1];$case=@($plan.arms|Where-Object{$_.name-eq$arm})[0];$path=Join-Path $env:JET3_WORK "$CaseName.mdb";$result=[ordered]@{case=$arm;replica=$rep;source_revision=[string]$plan.source_revision;matrix_sha256=(Identity (Join-Path $env:JET3_WORK 'matrix.json')).sha256;environment=$null;status='fail';error=$null;capture=$null;identity=$null}
try{$probe=New-Object -ComObject DAO.DBEngine.36;try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});if($dll.Count-ne1){throw 'DAO DLL absent'};$result.environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=[IntPtr]::Size*8;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;dll_path=$dll[0].FileName;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $probe};Create-Case $path $case $plan;$result.capture=Capture $path $case;$result.identity=Identity $path;Copy-Item -LiteralPath $path -Destination (Join-Path $env:JET3_OUTBOX "$CaseName.mdb");$result.status='pass'}catch{$result.error=@{type=$_.Exception.GetType().FullName;message=$_.Exception.Message;hresult=[int]$_.Exception.HResult;stack=[string]$_.ScriptStackTrace}}
Write-Json $result (Join-Path $env:JET3_OUTBOX "$CaseName.json")
if($result.status-ne'pass'){exit 1}
