param([string]$CaseName='')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$Cp=[Text.Encoding]::GetEncoding(1252,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback))
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Hex([byte[]]$b){[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()}
function Hex-Bytes([string]$s){$b=[byte[]]::new($s.Length/2);for($i=0;$i-lt$b.Length;$i++){$b[$i]=[Convert]::ToByte($s.Substring(2*$i,2),16)};return ,$b}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,((ConvertTo-Json -InputObject $v -Depth 100 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function Set-Cell($rs,[string]$name,$value){$fs=$f=$null;try{$fs=$rs.Fields;$f=$fs.Item($name);$a=[object[]]::new(1);$a[0]=$value;[void]$f.GetType().InvokeMember('Value',[Reflection.BindingFlags]::SetProperty,$null,$f,$a)}finally{Release $f;Release $fs}}
function Failure($record,$engine){$numbers=@();$errors=$item=$null;try{$errors=$engine.Errors;for($i=0;$i-lt$errors.Count;$i++){$item=$errors.Item($i);$numbers+=[int]$item.Number;Release $item;$item=$null}}finally{Release $item;Release $errors};$e=$record.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;numbers=@($numbers);stack=[string]$record.ScriptStackTrace}}
function Convert-Value($value,[int]$type){if($null-eq$value){return [DBNull]::Value};if($type-eq4){return [int]$value};$b=Hex-Bytes([string]$value);if($type-eq11){return ,([byte[]]$b)};return $Cp.GetString($b)}
function Read-Properties($field){$a=@();$p=$null;try{foreach($p in $field.Properties){$v=$p.Value;$n=$null-eq$v-or[Convert]::IsDBNull($v);$a+=@{name=[string]$p.Name;type=[int]$p.Type;is_null=$n;value=if($n){$null}else{[string]$v}};Release $p;$p=$null}}finally{Release $p};return ,$a}
function Read-Fields($table){$a=@();$fs=$f=$null;try{$fs=$table.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$a+=@{name=[string]$f.Name;type=[int]$f.Type;size=[int]$f.Size;attributes=[int]$f.Attributes;required=[bool]$f.Required;allow_zero_length=[bool]$f.AllowZeroLength;properties=Read-Properties $f};Release $f;$f=$null}}finally{Release $f;Release $fs};return ,$a}
function Read-Indexes($table){$a=@();$xs=$x=$fs=$f=$null;try{$xs=$table.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$keys=@();$fs=$x.Fields;for($j=0;$j-lt$fs.Count;$j++){$f=$fs.Item($j);$keys+=@{name=[string]$f.Name;attributes=[int]$f.Attributes};Release $f;$f=$null};Release $fs;$fs=$null;$a+=@{name=[string]$x.Name;primary=[bool]$x.Primary;unique=[bool]$x.Unique;required=[bool]$x.Required;foreign=[bool]$x.Foreign;ignore_nulls=[bool]$x.IgnoreNulls;fields=@($keys)};Release $x;$x=$null}}finally{Release $f;Release $fs;Release $x;Release $xs};return ,$a}
function Read-Row($rs,$specs){$fs=$f=$null;$v=[ordered]@{};try{$fs=$rs.Fields;foreach($s in $specs){$name=[string]$s.name;$f=$fs.Item($name);$x=$f.Value;if($null-eq$x-or[Convert]::IsDBNull($x)){$v[$name]=$null}elseif([int]$s.type-eq4){$v[$name]=[int]$x}elseif([int]$s.type-eq11){$v[$name]=Hex([byte[]]$x)}else{$v[$name]=Hex($Cp.GetBytes([string]$x))};Release $f;$f=$null}}finally{Release $f;Release $fs};return $v}
function Read-Table($db,[string]$name,$specs){$td=$rs=$xs=$x=$null;try{$td=$db.TableDefs.Item($name);$out=@{name=$name;attributes=[int]$td.Attributes;fields=(Read-Fields $td);indexes=(Read-Indexes $td);rows=@();index_reads=@{}};$rs=$db.OpenRecordset($name,4);while(-not$rs.EOF){$out.rows+=,(Read-Row $rs $specs);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$xs=$td.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$ix=[string]$x.Name;$rs=$db.OpenRecordset($name,1);$rs.Index=$ix;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};$tr=@();while(-not$rs.EOF){$tr+=,(Read-Row $rs $specs);$rs.MoveNext()};$keyName=[string]$x.Fields.Item(0).Name;$keys=@($out.rows|ForEach-Object{$_.$keyName}|Where-Object{$null-ne$_}|Sort-Object -Unique)+@(999999);$seeks=@();foreach($key in $keys){$rs.Seek('=',[int]$key);$seeks+=@{query=[int]$key;row=if($rs.NoMatch){$null}else{Read-Row $rs $specs}}};$out.index_reads[$ix]=@{traversal=@($tr);seek=@($seeks)};$rs.Close();Release $rs;$rs=$null;Release $x;$x=$null};return $out}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $x;Release $xs;Release $td}}
function Capture([string]$path,$case,[string]$file){$before=Identity $path;$e=$db=$rels=$r=$rfs=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$pf=@([pscustomobject]@{name='Id';type=4},[pscustomobject]@{name='Label';type=10});$ra=@();$rels=$db.Relations;for($i=0;$i-lt$rels.Count;$i++){$r=$rels.Item($i);$fa=@();$rfs=$r.Fields;for($j=0;$j-lt$rfs.Count;$j++){$rf=$rfs.Item($j);$fa+=@{name=[string]$rf.Name;foreign_name=[string]$rf.ForeignName};Release $rf;$rf=$null};Release $rfs;$rfs=$null;$ra+=@{name=[string]$r.Name;table=[string]$r.Table;foreign_table=[string]$r.ForeignTable;attributes=[int]$r.Attributes;fields=@($fa)};Release $r;$r=$null};$snap=@{version=[string]$db.Version;tables=@($db.TableDefs|ForEach-Object{[string]$_.Name}|Sort-Object);relations=@($ra);parent=Read-Table $db 'Parent' $pf;child=Read-Table $db 'Child' $case.fields}}finally{Release $rf;Release $rfs;Release $r;Release $rels;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($before.sha256-ne$after.sha256){throw 'Read-only capture changed image'};Copy-Item -LiteralPath $path -Destination (Join-Path $env:JET3_OUTBOX $file);return @{file=$file;before=$before;after=$after;snapshot=$snap}}
function Set-Row($rs,$case,[string]$table,$row,[bool]$SkipAuto=$false){$specs=if($table-eq'Parent'){@([pscustomobject]@{name='Id';type=4},[pscustomobject]@{name='Label';type=10})}else{$case.fields};if($row.Count-ne$specs.Count){throw 'Row arity'};for($i=0;$i-lt$specs.Count;$i++){if($SkipAuto-and$table-eq'Child'-and$i-eq0-and[int]$specs[$i].attributes-eq16){continue};Set-Cell $rs ([string]$specs[$i].name) (Convert-Value $row[$i] ([int]$specs[$i].type))}}
function Apply-One([string]$path,$case,$op,[bool]$ExpectFailure){$before=Identity $path;$e=$db=$rs=$null;$error=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$false);$table=[string]$op.table;$rs=$db.OpenRecordset($table,1);$rs.Index=if($table-eq'Parent'){'ByParent'}else{'ByChild'};$kind=[string]$op.kind;if($kind-eq'insert'){$rs.AddNew();Set-Row $rs $case $table $op.row;$rs.Update()}else{$rs.Seek('=',[int]$op.id);if($rs.NoMatch){throw 'Target absent'};if($kind-eq'delete'){$rs.Delete()}else{$rs.Edit();if($kind-eq'replace'){Set-Row $rs $case $table $op.row $true}elseif($kind-eq'field'){$spec=if($table-eq'Parent'){@([pscustomobject]@{name='Id';type=4},[pscustomobject]@{name='Label';type=10})}else{$case.fields};$c=[int]$op.column;Set-Cell $rs ([string]$spec[$c].name) (Convert-Value $op.value ([int]$spec[$c].type))}else{throw 'Unknown operation'};$rs.Update()}}}catch{$error=Failure $_ $e;if(-not$ExpectFailure){throw}}finally{if($null-ne$rs){try{if($rs.EditMode-ne0){$rs.CancelUpdate()};$rs.Close()}catch{}};Release $rs;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e};$after=Identity $path;if($ExpectFailure-and$null-eq$error){throw 'Expected refusal succeeded'};@{request=$op;before=$before;after=$after;status=if($null-eq$error){'success'}else{'rejected'};error=$error}}
function Apply-All([string]$path,$case,$ops){$a=@();foreach($op in $ops){$a+=,(Apply-One $path $case $op $false)};return ,$a}
if($CaseName-eq''){
 $input=Join-Path $env:JET3_WORK 'input';Expand-Archive -LiteralPath (Join-Path $env:JET3_WORK 'acceptance-input.zip') -DestinationPath $input
 $matrix=Get-Content -Raw -LiteralPath (Join-Path $input 'matrix.json')|ConvertFrom-Json;$fails=@()
 foreach($case in $matrix.arms){for($rep=1;$rep-le2;$rep++){$name="$($case.name)-r$rep";$exe="$env:SystemRoot\SysWOW64\WindowsPowerShell\v1.0\powershell.exe";$p=Start-Process -FilePath $exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-CaseName',$name) -Wait -PassThru;if($p.ExitCode-ne0){$fails+=$name}}}
 if($fails.Count){throw ('Workers failed: '+($fails-join','))};exit 0
}
$root=Join-Path $env:JET3_WORK 'input';$parts=$CaseName-split'-r';$arm=$parts[0];$rep=[int]$parts[1];$matrix=Get-Content -Raw -LiteralPath (Join-Path $root 'matrix.json')|ConvertFrom-Json;$case=@($matrix.arms|Where-Object{$_.name-eq$arm})[0];$recipe=Get-Content -Raw -LiteralPath (Join-Path $root "recipe-$arm.json")|ConvertFrom-Json
$result=[ordered]@{case=$arm;replica=$rep;matrix_sha256=(Identity (Join-Path $root 'matrix.json')).sha256;recipe_sha256=(Identity (Join-Path $root "recipe-$arm.json")).sha256;environment=$null;status='fail';error=$null;stages=@();refusals=@();native=@()}
try{$probe=New-Object -ComObject DAO.DBEngine.36;try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});$result.environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=[IntPtr]::Size*8;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $probe}
 $control=Join-Path $env:JET3_WORK "$CaseName-control.mdb";Copy-Item -LiteralPath (Join-Path $root "inputs/native/$CaseName.mdb") -Destination $control
 foreach($stage in $recipe.stages){$entry=@{name=[string]$stage.name;roles=@{};control_operations=$null};if($stage.operations.Count){$entry.control_operations=Apply-All $control $case $stage.operations};foreach($role in @('candidate','native-rust')){$source=Join-Path $root "local/$role-$CaseName/$($stage.name).mdb";$file="$CaseName-$($stage.name)-$role.mdb";$entry.roles[$role]=Capture $source $case $file};$file="$CaseName-$($stage.name)-control.mdb";$entry.roles.control=Capture $control $case $file;$result.stages+=,$entry}
 foreach($refusal in $recipe.refusals){$entry=@{name=[string]$refusal.name;expected_number=[int]$refusal.number;roles=@{}};foreach($role in @('candidate','control')){$source=if($role-eq'candidate'){Join-Path $root "inputs/$CaseName.mdb"}else{Join-Path $root "inputs/native/$CaseName.mdb"};$path=Join-Path $env:JET3_WORK "$CaseName-refusal-$($refusal.name)-$role.mdb";Copy-Item -LiteralPath $source -Destination $path;$operation=Apply-One $path $case $refusal.operation $true;$file="$CaseName-refusal-$($refusal.name)-$role.mdb";$capture=Capture $path $case $file;$entry.roles[$role]=@{operation=$operation;capture=$capture}};$result.refusals+=,$entry}
 foreach($role in @('candidate','control','native-rust')){$source=if($role-eq'control'){$control}else{Join-Path $root "local/$role-$CaseName/ordered-deletes.mdb"};$path=Join-Path $env:JET3_WORK "$CaseName-native-next-$role.mdb";Copy-Item -LiteralPath $source -Destination $path;$ops=Apply-All $path $case $recipe.native;$capture=Capture $path $case "$CaseName-native-next-$role.mdb";$result.native+=@{role=$role;operations=$ops;capture=$capture}}
 $result.status='pass'}catch{$result.error=@{type=$_.Exception.GetType().FullName;message=$_.Exception.Message;hresult=[int]$_.Exception.HResult;stack=[string]$_.ScriptStackTrace}}
Write-Json $result (Join-Path $env:JET3_OUTBOX "$CaseName.json");if($result.status-ne'pass'){exit 1}
