Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item $p).Length;sha256=(Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Hex([byte[]]$b){[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()}
function Hash-Bytes([byte[]]$b){$h=[Security.Cryptography.SHA256]::Create();try{Hex($h.ComputeHash($b))}finally{$h.Dispose()}}
function Norm($v){if($null-eq$v-or[Convert]::IsDBNull($v)){return $null};if($v-is[byte[]]){return @{kind='bytes';length=$v.Length;sha256=Hash-Bytes([byte[]]$v)}};if($v-is[datetime]){return @{kind='date';oa=([datetime]$v).ToOADate()}};if($v-is[bool]){return [bool]$v};if($v-is[byte]-or$v-is[int16]-or$v-is[int32]-or$v-is[int64]){return [long]$v};if($v-is[string]-and$v.Length-gt1024){$bytes=[Text.Encoding]::UTF8.GetBytes([string]$v);return @{kind='text';length=$v.Length;sha256=Hash-Bytes $bytes}};return [string]$v}
function Props($o){$a=@();$ps=$p=$null;try{$ps=$o.Properties;for($i=0;$i-lt$ps.Count;$i++){$p=$ps.Item($i);$a+=@{ordinal=$i;name=[string]$p.Name;type=[int]$p.Type;value=Norm $p.Value};Release $p;$p=$null}}finally{Release $p;Release $ps};return ,$a}
function Row($rs){$r=[ordered]@{};$fs=$f=$null;try{$fs=$rs.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$r[[string]$f.Name]=Norm $f.Value;Release $f;$f=$null}}finally{Release $f;Release $fs};return $r}
function Rows($db,[string]$name){$a=@();$rs=$null;try{$rs=$db.OpenRecordset($name,4);while(-not$rs.EOF){$a+=,(Row $rs);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs};return ,$a}
function Read-Table($db,$td,[int]$ordinal){$fs=$f=$xs=$x=$xfs=$xf=$rs=$null;try{$fields=@();$fs=$td.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$fields+=@{ordinal=$i;name=[string]$f.Name;type=[int]$f.Type;size=[int]$f.Size;attributes=[int]$f.Attributes;required=[bool]$f.Required;allow_zero_length=[bool]$f.AllowZeroLength;properties=Props $f};Release $f;$f=$null};Release $fs;$fs=$null;$indexes=@();$xs=$td.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$keys=@();$xfs=$x.Fields;for($j=0;$j-lt$xfs.Count;$j++){$xf=$xfs.Item($j);$keys+=@{ordinal=$j;name=[string]$xf.Name;attributes=[int]$xf.Attributes;properties=Props $xf};Release $xf;$xf=$null};Release $xfs;$xfs=$null;$traversal=@();$rs=$db.OpenRecordset([string]$td.Name,1);$rs.Index=[string]$x.Name;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};while(-not$rs.EOF){$traversal+=,(Row $rs);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$indexes+=@{ordinal=$i;name=[string]$x.Name;primary=[bool]$x.Primary;unique=[bool]$x.Unique;required=[bool]$x.Required;foreign=[bool]$x.Foreign;ignore_nulls=[bool]$x.IgnoreNulls;fields=$keys;properties=Props $x;traversal=$traversal};Release $x;$x=$null};Release $xs;$xs=$null;@{ordinal=$ordinal;name=[string]$td.Name;attributes=[int]$td.Attributes;properties=Props $td;fields=$fields;indexes=$indexes;rows=@(Rows $db ([string]$td.Name))}}finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $xf;Release $xfs;Release $x;Release $xs;Release $f;Release $fs}}
function Read-Tables($db){$a=@();$tds=$td=$null;try{$tds=$db.TableDefs;for($i=0;$i-lt$tds.Count;$i++){$td=$tds.Item($i);$name=[string]$td.Name;if(-not$name.StartsWith('MSys')){$a+=Read-Table $db $td $i};Release $td;$td=$null}}finally{Release $td;Release $tds};return ,$a}
function Read-Relations($db){$a=@();$rs=$r=$fs=$f=$null;try{$rs=$db.Relations;for($i=0;$i-lt$rs.Count;$i++){$r=$rs.Item($i);$keys=@();$fs=$r.Fields;for($j=0;$j-lt$fs.Count;$j++){$f=$fs.Item($j);$keys+=@{ordinal=$j;name=[string]$f.Name;foreign_name=[string]$f.ForeignName;properties=Props $f};Release $f;$f=$null};Release $fs;$fs=$null;$a+=@{ordinal=$i;name=[string]$r.Name;table=[string]$r.Table;foreign_table=[string]$r.ForeignTable;attributes=[int]$r.Attributes;properties=Props $r;fields=$keys};Release $r;$r=$null}}finally{Release $f;Release $fs;Release $r;Release $rs};return ,$a}
function Read-Queries($db){$a=@();$qs=$q=$null;try{$qs=$db.QueryDefs;for($i=0;$i-lt$qs.Count;$i++){$q=$qs.Item($i);$a+=@{ordinal=$i;name=[string]$q.Name;type=[int]$q.Type;sql=[string]$q.SQL;properties=Props $q};Release $q;$q=$null}}finally{Release $q;Release $qs};return ,$a}
$e=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});$environment=@{provider='DAO.DBEngine.36';version=[string]$e.Version;bits=[IntPtr]::Size*8;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;ansi=[Globalization.CultureInfo]::CurrentCulture.TextInfo.ANSICodePage;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $e}
$result=@{document_type='jet3_schema_candidate_complete_readback';environment=$environment;files=@();status='pass'}
foreach($file in @(Get-ChildItem -LiteralPath $env:JET3_WORK -Filter '*.mdb'|Sort-Object Name)){$before=Identity $file.FullName;$e=$db=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($file.FullName,$false,$true);$result.files+=@{file=$file.Name;identity=$before;tables=@(Read-Tables $db);relations=@(Read-Relations $db);querydefs=@(Read-Queries $db)}}finally{if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $file.FullName;if($before.sha256-cne$after.sha256){throw('Read changed '+$file.Name)}}
[IO.File]::WriteAllText((Join-Path $env:JET3_OUTBOX 'RESULT.json'),((ConvertTo-Json $result -Depth 100 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))
