param([int]$Replica=0)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
if([IntPtr]::Size-ne4){throw 'Expected x86 DAO'}
$Cp=[Text.Encoding]::GetEncoding(1252,(New-Object Text.EncoderExceptionFallback),(New-Object Text.DecoderExceptionFallback))
function Release($x){if($null-ne$x-and[Runtime.InteropServices.Marshal]::IsComObject($x)){[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($x)}}
function Identity([string]$p){@{size=(Get-Item -LiteralPath $p).Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}}
function Hex([byte[]]$b){[BitConverter]::ToString($b).Replace('-','').ToLowerInvariant()}
function Hex-Bytes([string]$s){$b=[byte[]]::new($s.Length/2);for($i=0;$i-lt$b.Length;$i++){$b[$i]=[Convert]::ToByte($s.Substring(2*$i,2),16)};return ,$b}
function Write-Json($v,[string]$p){[IO.File]::WriteAllText($p,((ConvertTo-Json -InputObject $v -Depth 100 -Compress)+"`n"),(New-Object Text.UTF8Encoding($false)))}
function Name-Record([string]$s){$encoded=$null;$ok=$true;try{$encoded=[BitConverter]::ToString($Cp.GetBytes([string]$s)).Replace('-','').ToLowerInvariant()}catch{$ok=$false};@{value=$s;utf16le=Hex([Text.Encoding]::Unicode.GetBytes($s));cp1252=if($ok){$encoded}else{$null};cp1252_defined=$ok;characters=$s.Length}}
function Error-Record($record,$engine){$numbers=@();$es=$ei=$null;try{if($null-ne$engine){$es=$engine.Errors;for($i=0;$i-lt$es.Count;$i++){$ei=$es.Item($i);$numbers+=[int]$ei.Number;Release $ei;$ei=$null}}}finally{Release $ei;Release $es};$e=$record.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;numbers=@($numbers);stack=[string]$record.ScriptStackTrace}}
function Set-Property($owner,[string]$name,$value){$a=[object[]]::new(1);$a[0]=$value;[void]$owner.GetType().InvokeMember($name,[Reflection.BindingFlags]::SetProperty,$null,$owner,$a)}
function Set-Cell($rs,[string]$name,$value){$fs=$f=$null;try{$fs=$rs.Fields;$f=$fs.Item($name);Set-Property $f 'Value' $value}finally{Release $f;Release $fs}}
function Convert-Value($value,[int]$type){if($null-eq$value){return [DBNull]::Value};if($type-eq4){return [int]$value};return [string]$value}
function New-Database([string]$path){$e=$w=$db=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$w=$e.Workspaces.Item(0);$db=$w.CreateDatabase($path,';LANGID=0x0409;CP=1252;COUNTRY=0',32);$db.Close();Release $db;$db=$null}finally{if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $w;Release $e}}
function Add-Table($db,$spec){
 $td=$fs=$f=$xs=$x=$xf=$rs=$null
 try{$td=$db.CreateTableDef([string]$spec.name)
  foreach($s in $spec.fields){$f=if([int]$s.type-eq4){$td.CreateField([string]$s.name,4)}else{$td.CreateField([string]$s.name,[int]$s.type,[int]$s.size)};if([bool]$s.allow_zero_length){Set-Property $f 'AllowZeroLength' $true};$td.Fields.Append($f);Release $f;$f=$null}
  foreach($ix in $spec.indexes){$x=$td.CreateIndex([string]$ix.name);$xf=$x.CreateField([string]$ix.field);$x.Fields.Append($xf);$x.Primary=[bool]$ix.primary;$x.Unique=[bool]$ix.unique;$td.Indexes.Append($x);Release $xf;$xf=$null;Release $x;$x=$null}
  $db.TableDefs.Append($td);Release $td;$td=$null
  if($spec.rows.Count){$rs=$db.OpenRecordset([string]$spec.name,2);foreach($row in $spec.rows){$rs.AddNew();foreach($s in $spec.fields){Set-Cell $rs ([string]$s.name) (Convert-Value $row.([string]$s.name) ([int]$s.type))};$rs.Update()};$rs.Close();Release $rs;$rs=$null}
 }finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $xf;Release $x;Release $xs;Release $f;Release $fs;Release $td}
}
function Add-Relation($db,$spec){$r=$f=$null;try{$r=$db.CreateRelation([string]$spec.name,[string]$spec.parent,[string]$spec.child,0);$f=$r.CreateField([string]$spec.parent_field);$f.ForeignName=[string]$spec.child_field;$r.Fields.Append($f);$db.Relations.Append($r)}finally{Release $f;Release $r}}
function Read-Properties($owner){$a=@();$ps=$p=$null;try{$ps=$owner.Properties;for($i=0;$i-lt$ps.Count;$i++){$p=$ps.Item($i);$v=$p.Value;$a+=@{ordinal=$i;name=Name-Record([string]$p.Name);type=[int]$p.Type;is_null=($null-eq$v-or[Convert]::IsDBNull($v));value=if($null-eq$v-or[Convert]::IsDBNull($v)){$null}else{[string]$v}};Release $p;$p=$null}}finally{Release $p;Release $ps};return ,$a}
function Read-Fields($td){$a=@();$fs=$f=$null;try{$fs=$td.Fields;for($i=0;$i-lt$fs.Count;$i++){$f=$fs.Item($i);$a+=@{ordinal=$i;name=Name-Record([string]$f.Name);type=[int]$f.Type;size=[int]$f.Size;attributes=[int]$f.Attributes;required=[bool]$f.Required;allow_zero_length=[bool]$f.AllowZeroLength;properties=Read-Properties $f};Release $f;$f=$null}}finally{Release $f;Release $fs};return ,$a}
function Read-Indexes($td){$a=@();$xs=$x=$fs=$f=$null;try{$xs=$td.Indexes;for($i=0;$i-lt$xs.Count;$i++){$x=$xs.Item($i);$keys=@();$fs=$x.Fields;for($j=0;$j-lt$fs.Count;$j++){$f=$fs.Item($j);$keys+=@{ordinal=$j;name=Name-Record([string]$f.Name);attributes=[int]$f.Attributes};Release $f;$f=$null};Release $fs;$fs=$null;$a+=@{ordinal=$i;name=Name-Record([string]$x.Name);primary=[bool]$x.Primary;unique=[bool]$x.Unique;required=[bool]$x.Required;foreign=[bool]$x.Foreign;ignore_nulls=[bool]$x.IgnoreNulls;fields=@($keys);properties=Read-Properties $x};Release $x;$x=$null}}finally{Release $f;Release $fs;Release $x;Release $xs};return ,$a}
function Read-Row($rs,$specs){$row=[ordered]@{};$fs=$f=$null;try{$fs=$rs.Fields;foreach($s in $specs){$f=$fs.Item([string]$s.name.value);$v=$f.Value;$row[[string]$s.name.value]=if($null-eq$v-or[Convert]::IsDBNull($v)){$null}elseif([int]$s.type-eq4){[int]$v}else{Hex($Cp.GetBytes([string]$v))};Release $f;$f=$null}}finally{Release $f;Release $fs};return $row}
function Seek-Value($value,[int]$type){if($null-eq$value){return [DBNull]::Value};if($type-eq4){return [int]$value};return $Cp.GetString((Hex-Bytes ([string]$value)))}
function Read-Table($db,$td){
 $specs=Read-Fields $td;$out=[ordered]@{ordinal=0;name=Name-Record([string]$td.Name);attributes=[int]$td.Attributes;properties=Read-Properties $td;fields=$specs;indexes=Read-Indexes $td;rows=@();index_reads=[ordered]@{}};$rs=$xs=$x=$fs=$f=$null
 try{$rs=$db.OpenRecordset([string]$td.Name,4);while(-not$rs.EOF){$out.rows+=,(Read-Row $rs $specs);$rs.MoveNext()};$rs.Close();Release $rs;$rs=$null;$xs=$td.Indexes
  for($i=0;$i-lt$xs.Count;$i++){
   $x=$xs.Item($i);$name=[string]$x.Name;$fs=$x.Fields;if($fs.Count-ne1){throw 'Expected one-column index'};$f=$fs.Item(0);$field=[string]$f.Name;Release $f;$f=$null;Release $fs;$fs=$null;$ks=@($specs|Where-Object{$_.name.value-ceq$field});if($ks.Count-ne1){throw 'Index field absent'}
   $tr=@();$seeks=@();$readError=$null
   try{$rs=$db.OpenRecordset([string]$td.Name,1);$rs.Index=$name;if(-not($rs.BOF-and$rs.EOF)){$rs.MoveFirst()};while(-not$rs.EOF){$tr+=,(Read-Row $rs $specs);$rs.MoveNext()};$queries=@();$seen=@{};foreach($row in $tr){$v=$row[$field];$token=if($null-eq$v){'<NULL>'}else{[string]$v};if(-not$seen.ContainsKey($token)){$seen[$token]=$true;$queries+=,$v}};$missing=if([int]$ks[0].type-eq4){2147483000}else{Hex($Cp.GetBytes('~missing~'))};$queries+=,$missing;foreach($v in $queries){$seek=Seek-Value $v ([int]$ks[0].type);$rs.Seek('=',$seek);$seeks+=@{query=$v;no_match=[bool]$rs.NoMatch;row=if($rs.NoMatch){$null}else{Read-Row $rs $specs}}}}
   catch{$e=$_.Exception;while($null-ne$e.InnerException){$e=$e.InnerException};$readError=@{type=$e.GetType().FullName;message=$e.Message;hresult=[int]$e.HResult;stack=[string]$_.ScriptStackTrace}}
   finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;$rs=$null}
   $out.index_reads[$name]=@{field=$field;traversal=@($tr);seek=@($seeks);error=$readError};Release $x;$x=$null
  }
 }finally{if($null-ne$rs){try{$rs.Close()}catch{}};Release $rs;Release $f;Release $fs;Release $x;Release $xs};return $out
}
function Capture([string]$path){$before=Identity $path;$e=$db=$tds=$td=$rels=$r=$rfs=$rf=$null;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$true);$tables=@();$tds=$db.TableDefs;for($i=0;$i-lt$tds.Count;$i++){$td=$tds.Item($i);if(-not([string]$td.Name).StartsWith('MSys')){$t=Read-Table $db $td;$t.ordinal=$i;$tables+=,$t};Release $td;$td=$null};$relations=@();$rels=$db.Relations;for($i=0;$i-lt$rels.Count;$i++){$r=$rels.Item($i);$keys=@();$rfs=$r.Fields;for($j=0;$j-lt$rfs.Count;$j++){$rf=$rfs.Item($j);$keys+=@{name=Name-Record([string]$rf.Name);foreign_name=Name-Record([string]$rf.ForeignName)};Release $rf;$rf=$null};Release $rfs;$rfs=$null;$relations+=@{ordinal=$i;name=Name-Record([string]$r.Name);table=Name-Record([string]$r.Table);foreign_table=Name-Record([string]$r.ForeignTable);attributes=[int]$r.Attributes;fields=@($keys)};Release $r;$r=$null};$snapshot=@{version=[string]$db.Version;tables=@($tables);relations=@($relations)}}finally{Release $rf;Release $rfs;Release $r;Release $rels;Release $td;Release $tds;if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e;[GC]::Collect();[GC]::WaitForPendingFinalizers()};$after=Identity $path;if($before.sha256-cne$after.sha256){throw 'Read-only capture changed image'};return @{before=$before;after=$after;snapshot=$snapshot}}
function Attempt-Name($db,[string]$role,[string]$name){$td=$f=$x=$xf=$null;try{if($role-eq'table'){$td=$db.CreateTableDef($name);$f=$td.CreateField('Id',4);$td.Fields.Append($f);$db.TableDefs.Append($td)}elseif($role-eq'column'){$td=$db.TableDefs.Item('Probe');$f=$td.CreateField($name,10,32);$td.Fields.Append($f)}elseif($role-eq'index'){$td=$db.TableDefs.Item('Probe');$x=$td.CreateIndex($name);$xf=$x.CreateField('Value');$x.Fields.Append($xf);$td.Indexes.Append($x)}else{throw 'Unknown role'};return $true}finally{Release $xf;Release $x;Release $f;Release $td}}
function Run-Accepted($case,[int]$replica){$file="r$replica-accepted-$($case.id).mdb";$path=Join-Path $env:JET3_WORK $file;$e=$db=$null;$error=$null;New-Database $path;try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$false);foreach($table in $case.tables){Add-Table $db $table};foreach($relation in $case.relations){Add-Relation $db $relation}}catch{$error=Error-Record $_ $e}finally{if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e};$capture=Capture $path;Copy-Item $path (Join-Path $env:JET3_OUTBOX $file);@{id=[string]$case.id;file=$file;creation_error=$error;capture=$capture}}
function Run-Probe($probe,[int]$replica){$file="r$replica-probe-$($probe.id).mdb";$path=Join-Path $env:JET3_WORK $file;New-Database $path;$e=$db=$null;$attempts=@();try{$e=New-Object -ComObject DAO.DBEngine.36;$db=$e.OpenDatabase($path,$false,$false);if($probe.role-ne'table'){$base=@{name='Probe';fields=@(@{name='Id';type=4;size=4;allow_zero_length=$false},@{name='Value';type=4;size=4;allow_zero_length=$false});indexes=@();rows=@()};Add-Table $db $base};foreach($name in $probe.names){$error=$null;$ok=$false;try{$ok=Attempt-Name $db ([string]$probe.role) ([string]$name)}catch{$error=Error-Record $_ $e};$attempts+=@{requested=Name-Record([string]$name);success=$ok;error=$error}}}finally{if($null-ne$db){try{$db.Close()}catch{}};Release $db;Release $e};$capture=Capture $path;Copy-Item $path (Join-Path $env:JET3_OUTBOX $file);@{id=[string]$probe.id;role=[string]$probe.role;file=$file;attempts=@($attempts);capture=$capture}}
$matrixPath=Join-Path $env:JET3_WORK 'matrix.json';$matrix=Get-Content -Raw -Encoding UTF8 -LiteralPath $matrixPath|ConvertFrom-Json
if($Replica-eq0){$workers=@();$failed=$false;$shell=Join-Path $env:WINDIR 'SysWOW64\WindowsPowerShell\v1.0\powershell.exe';foreach($r in 1..[int]$matrix.replicas){&$shell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $PSCommandPath -Replica $r;$code=$LASTEXITCODE;$workerPath=Join-Path $env:JET3_OUTBOX "r$r-result.json";$workers+=@{replica=$r;exit_code=$code;result=if(Test-Path $workerPath){Identity $workerPath}else{$null}};if($code-ne0){$failed=$true}};Write-Json @{document_type='schema_name_workers';matrix=Identity $matrixPath;workers=$workers} (Join-Path $env:JET3_OUTBOX 'workers.json');if($failed){exit 1};exit 0}
$result=[ordered]@{document_type='dao_cp1252_schema_names';replica=$Replica;matrix=Identity $matrixPath;environment=$null;accepted=@();probes=@();status='fail';error=$null}
try{$probe=New-Object -ComObject DAO.DBEngine.36;try{$dll=@([Diagnostics.Process]::GetCurrentProcess().Modules|Where-Object{$_.ModuleName-ieq'dao360.dll'});$result.environment=@{provider='DAO.DBEngine.36';version=[string]$probe.Version;bits=32;os=[Environment]::OSVersion.VersionString;culture=[Globalization.CultureInfo]::CurrentCulture.Name;ansi=[Globalization.CultureInfo]::CurrentCulture.TextInfo.ANSICodePage;dll_version=$dll[0].FileVersionInfo.FileVersion;dll_sha256=(Identity $dll[0].FileName).sha256}}finally{Release $probe};foreach($case in $matrix.accepted){$result.accepted+=,(Run-Accepted $case $Replica)};foreach($case in $matrix.probes){$result.probes+=,(Run-Probe $case $Replica)};$result.status='pass'}catch{$result.error=Error-Record $_ $null}
Write-Json $result (Join-Path $env:JET3_OUTBOX "r$Replica-result.json");if($result.status-ne'pass'){exit 1}
