# Allocation lifecycles (EXP-0254/0256): one x86 worker per case builds a DAO control, mutates
# it beside each Rust checkpoint, applies native writes to both, and in the continuation round
# repeats Rust's edits of the native DAO output. Rows are generated by allocation_lifecycle.cs
# and compared through canonical SHA-256 digests.
param([string]$CaseName = '')
. (Join-Path $PSScriptRoot 'Common.ps1')
. (Join-Path $PSScriptRoot 'Rows.ps1')
Add-Type -Path (Join-Path $PSScriptRoot 'allocation_lifecycle.cs')

function Set-RecipeRow($Handles, $Case, [int]$Id, [int]$Seed) {
    Set-Property $Handles[0] 'Value' ([int]$Id)
    if ([bool]$Case.payload) {
        $tag = if ($Seed % 13 -eq 0) { [DBNull]::Value } else { [int]($Seed % 17 - 8) }
        Set-Property $Handles[1] 'Value' $tag
        $memo = if ($Seed -eq 0) { [DBNull]::Value } else { [AllocationRows]::Memo($Seed) }
        Set-Property $Handles[2] 'Value' $memo
        $blob = if ($Seed -eq 1) { [DBNull]::Value } else { ,[AllocationRows]::Ole($Seed) }
        Set-Property $Handles[3] 'Value' $blob
    } else {
        for ($c = 0; $c -lt 4; $c++) { Set-Property $Handles[$c + 1] 'Value' ([AllocationRows]::Pad($Seed, $c)) }
    }
}

function Feed-Row($Hash, $Handles, $Case) {
    for ($c = 0; $c -lt $Handles.Count; $c++) {
        $value = $Handles[$c].Value; $bytes = $null
        if ($value -isnot [DBNull]) {
            switch ([int]$Case.fields[$c][1]) {
                4 { $bytes = [BitConverter]::GetBytes([int]$value) }
                11 { $bytes = [byte[]]$value }
                default { $bytes = [Text.Encoding]::GetEncoding(1252).GetBytes([string]$value) }
            }
        }
        [AllocationRows]::Feed($Hash, $bytes)
    }
}

function Row-Digest($Handles, $Case) {
    $hash = [Security.Cryptography.SHA256]::Create()
    try { Feed-Row $hash $Handles $Case; [AllocationRows]::Finish($hash) } finally { $hash.Dispose() }
}

function New-Control([string]$Path, $Case) {
    $engine = $workspaces = $workspace = $db = $tables = $table = $fields = $field = $indexes = $index = $keys = $key = $rs = $null; $handles = @()
    try {
        $engine = New-Object -ComObject DAO.DBEngine.36; $workspaces = $engine.Workspaces; $workspace = $workspaces.Item(0)
        $db = $workspace.CreateDatabase($Path, (Locale-String 'general'), 32); $tables = $db.TableDefs
        foreach ($name in @('Items', 'Notes')) {
            $script:endpoint = "$($Case.name)/create/$name"
            $table = $db.CreateTableDef($name); $fields = $table.Fields
            $specs = if ($name -eq 'Items') { $Case.fields } else { @(@('Id', 4, 4, $false), @('Body', 10, 64, $false)) }
            foreach ($spec in $specs) {
                $field = $table.CreateField([string]$spec[0], [int]$spec[1], [int]$spec[2])
                if ([bool]$spec[3]) { $field.Attributes = 1 }
                $fields.Append($field); Release $field; $field = $null
            }
            if ($name -eq 'Items') {
                $indexes = $table.Indexes
                foreach ($spec in $Case.indexes) {
                    $index = $table.CreateIndex([string]$spec.name); $keys = $index.Fields
                    $index.Primary = [bool]$spec.primary; $index.Unique = [bool]$spec.unique; $index.Required = [bool]$spec.required
                    foreach ($component in $spec.fields) {
                        $key = $index.CreateField([string]$Case.fields[[int]$component[0]][0])
                        if ([bool]$component[1]) { $key.Attributes = 1 }
                        $keys.Append($key); Release $key; $key = $null
                    }
                    $indexes.Append($index); Release $keys; $keys = $null; Release $index; $index = $null
                }
                Release $indexes; $indexes = $null
            }
            $tables.Append($table); Release $fields; $fields = $null; Release $table; $table = $null
        }
        $rs = $db.OpenRecordset('Notes', 2); $fields = $rs.Fields; $rs.AddNew()
        $field = $fields.Item('Id'); Set-Property $field 'Value' ([int]7); Release $field
        $field = $fields.Item('Body'); Set-Property $field 'Value' 'allocation-control'; Release $field; $field = $null
        $rs.Update(); Release $fields; $fields = $null; $rs.Close(); Release $rs
        $rs = $db.OpenRecordset('Items', 2); $fields = $rs.Fields
        foreach ($spec in $Case.fields) { $handles += ,$fields.Item([string]$spec[0]) }
        for ($id = 0; $id -lt $Case.initial_count; $id++) {
            $script:endpoint = "$($Case.name)/initial/$id"
            $rs.AddNew(); Set-RecipeRow $handles $Case $id $id; $rs.Update()
        }
    } finally {
        foreach ($handle in $handles) { Release $handle }
        Release $field; Release $fields; Release $key; Release $keys; Release $index; Release $indexes; Release $table; Release $tables
        Close-Com $rs $true; Close-Com $db $true; Release $workspace; Release $workspaces; Release $engine
    }
}

# Operations: insert {id, seed}, replace {old, id, seed}, delete {id}; located by ById Seek.
function Mutate([string]$Path, $Case, $Operations) {
    $before = Identity $Path; $engine = $db = $rs = $fields = $null; $handles = @()
    try {
        $engine = New-Object -ComObject DAO.DBEngine.36; $db = $engine.OpenDatabase($Path, $false, $false)
        $rs = $db.OpenRecordset('Items', 1); $rs.Index = 'ById'; $fields = $rs.Fields
        foreach ($spec in $Case.fields) { $handles += ,$fields.Item([string]$spec[0]) }
        foreach ($operation in $Operations) {
            $script:endpoint = "$($Case.name)/$($operation.kind)/$($operation.id)"
            if ($operation.kind -eq 'insert') {
                $rs.AddNew(); Set-RecipeRow $handles $Case ([int]$operation.id) ([int]$operation.seed); $rs.Update()
                continue
            }
            $old = if ($operation.kind -eq 'replace') { $operation.old } else { $operation.id }
            $rs.Seek('=', [int]$old)
            if ($rs.NoMatch) { throw 'Mutation key absent' }
            if ($operation.kind -eq 'delete') { $rs.Delete() }
            elseif ($operation.kind -eq 'replace') { $rs.Edit(); Set-RecipeRow $handles $Case ([int]$operation.id) ([int]$operation.seed); $rs.Update() }
            else { throw 'Unknown operation' }
        }
    } finally {
        foreach ($handle in $handles) { Release $handle }
        Release $fields; Close-Com $rs $true; Close-Com $db $true; Release $engine
    }
    @{ before = $before; after = (Identity $Path); count = @($Operations).Count }
}

# Schema, a digest of every row in ById order, every index traversal and one-field Seeks.
function Capture([string]$Path, $Case) {
    $before = Identity $Path; $engine = $db = $table = $tables = $rs = $fields = $null; $handles = @()
    $status = 'pass'; $errorDetail = $null; $snapshot = @{}
    try {
        $script:endpoint = "$($Case.name)/capture"
        $engine = New-Object -ComObject DAO.DBEngine.36; $db = $engine.OpenDatabase($Path, $false, $true)
        $snapshot = @{ version = [string]$db.Version; tables = @(Read-Names $db.TableDefs | Sort-Object); queries = @(Read-Names $db.QueryDefs)
                       relations = @(Read-Names $db.Relations); schema = @(); count = 0; digest = ''; notes = @(); index_reads = @{} }
        foreach ($name in @('Items', 'Notes')) {
            $tables = $db.TableDefs; $table = $tables.Item($name); Release $tables; $tables = $null
            $snapshot.schema += ,@{ name = $name; attributes = [int]$table.Attributes; fields = @(Read-Fields $table); indexes = @(Read-Indexes $table) }
            Release $table; $table = $null
        }
        $rs = $db.OpenRecordset('Items', 1); $rs.Index = 'ById'; $fields = $rs.Fields
        foreach ($spec in $Case.fields) { $handles += ,$fields.Item([string]$spec[0]) }
        $hash = [Security.Cryptography.SHA256]::Create(); $previous = -1
        try {
            if (-not ($rs.BOF -and $rs.EOF)) { $rs.MoveFirst() }
            while (-not $rs.EOF) {
                $id = [int]$handles[0].Value
                if ($id -le $previous) { throw 'Unordered primary traversal' }
                $previous = $id; Feed-Row $hash $handles $Case; $snapshot.count++; $rs.MoveNext()
            }
            $snapshot.digest = [AllocationRows]::Finish($hash)
        } finally { $hash.Dispose() }
        foreach ($index in $Case.indexes) {
            $rs.Index = [string]$index.name
            if (-not ($rs.BOF -and $rs.EOF)) { $rs.MoveFirst() }
            $ids = New-Object Collections.ArrayList
            while (-not $rs.EOF) { [void]$ids.Add([int]$handles[0].Value); $rs.MoveNext() }
            $read = @{ ids = @($ids.ToArray()); seek = @() }
            foreach ($query in $index.queries) {
                if ($query.Count -ne $index.fields.Count -or $query.Count -ne 1) { throw 'Complete one-field Seek arguments required' }
                $script:endpoint = "$($Case.name)/seek/$($index.name)/$($query[0])"
                $rs.Seek('=', [int]$query[0]); $id = $null; $rowDigest = $null
                if (-not $rs.NoMatch) { $id = [int]$handles[0].Value; $rowDigest = Row-Digest $handles $Case }
                $read.seek += ,@{ query = $query; id = $id; digest = $rowDigest }
            }
            $snapshot.index_reads[[string]$index.name] = $read
        }
        foreach ($handle in $handles) { Release $handle }
        $handles = @(); Release $fields; $fields = $null; $rs.Close(); Release $rs
        $rs = $db.OpenRecordset('Notes', 4); $fields = $rs.Fields
        $idField = $fields.Item('Id'); $bodyField = $fields.Item('Body')
        try {
            while (-not $rs.EOF) { $snapshot.notes += ,@([int]$idField.Value, [string]$bodyField.Value); $rs.MoveNext() }
        } finally { Release $idField; Release $bodyField }
    } catch { $status = 'error'; $errorDetail = Failure $_ } finally {
        foreach ($handle in $handles) { Release $handle }
        Release $fields; Close-Com $rs $true; Release $table; Release $tables; Close-Com $db $true; Release $engine
    }
    @{ file = [IO.Path]::GetFileName($Path); before = $before; after = (Identity $Path); status = $status; error = $errorDetail; snapshot = $snapshot }
}

Invoke-CaseSuite 'allocation-lifecycle.json' $CaseName $PSCommandPath 'dao_allocation_lifecycle_mutation_result' {
    param($Manifest, $Case)
    Invoke-ScalarCase $Manifest $Case 'mutated'
} @('.mdb', '.json', '.bin', '.log')
