#!/usr/bin/env python3
"""Generate the typed Rust outcome table from the closed protocol 1.2 inventory."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "oracle/windows-dao/protocol/v1_2/scenarios.json"
OUTPUT = ROOT / "crates/jet3-testkit/src/scenario_inventory_generated.rs"
ERROR_CLASSES = {
    "encrypted_database": "RejectedFormatErrorClass::EncryptedDatabase",
    "password_protected": "RejectedFormatErrorClass::PasswordProtected",
    "unsupported_version": "RejectedFormatErrorClass::UnsupportedVersion",
}


def load_entries(path: Path = INVENTORY) -> tuple[str, list[tuple[str, str]]]:
    raw = path.read_bytes()
    document: Any = json.loads(raw)
    if not isinstance(document, dict) or document.get("protocol_version") != "1.2.0":
        raise ValueError("expected the protocol 1.2.0 scenario inventory")
    if document.get("document_type") != "dao_scenario_inventory":
        raise ValueError("expected a DAO scenario inventory")
    scenarios = document.get("scenarios")
    if not isinstance(scenarios, list) or not scenarios:
        raise ValueError("expected a non-empty scenarios array")

    entries: list[tuple[str, str]] = []
    for index, scenario in enumerate(scenarios):
        if not isinstance(scenario, dict) or not isinstance(scenario.get("id"), str):
            raise ValueError(f"scenarios[{index}] has an invalid id")
        operation = scenario.get("operation")
        if not isinstance(operation, dict):
            raise ValueError(f"scenarios[{index}].operation is invalid")
        outcome = operation.get("expected_outcome")
        error_class = operation.get("error_class")
        if outcome == "success" and error_class is None:
            expectation = "ScenarioExpectation::Success"
        elif outcome == "expected_error" and error_class in ERROR_CLASSES:
            expectation = f"ScenarioExpectation::OpeningFailure({ERROR_CLASSES[error_class]})"
        else:
            raise ValueError(f"scenarios[{index}] has an unsupported outcome binding")
        entries.append((scenario["id"], expectation))

    identifiers = [identifier for identifier, _ in entries]
    if identifiers != sorted(identifiers) or len(identifiers) != len(set(identifiers)):
        raise ValueError("scenario ids must be unique and sorted")
    return hashlib.sha256(raw).hexdigest(), entries


def render(path: Path = INVENTORY) -> str:
    digest, entries = load_entries(path)
    lines = [
        "// @generated by tools/generate_scenario_inventory.py; do not edit.",
        "#[cfg(test)]",
        f'pub(super) const INVENTORY_SHA256: &str = "{digest}";',
        "pub(super) const SCENARIOS: &[(&str, ScenarioExpectation)] = &[",
    ]
    lines.extend(f'    ("{identifier}", {expectation}),' for identifier, expectation in entries)
    lines.extend([
        "];",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is stale")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} matches {INVENTORY.relative_to(ROOT)}")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
