#!/usr/bin/env python3
"""Generate typed Rust scenario bindings from the closed protocol 1.2 inventory."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "oracle/windows-dao/protocol/v1_2/scenarios.json"
OUTPUT = ROOT / "crates/jet3-testkit/src/scenario_inventory_generated.rs"
ERROR_CLASSES = {
    "encrypted_database": "RejectedFormatErrorClass::EncryptedDatabase",
    "password_protected": "RejectedFormatErrorClass::PasswordProtected",
    "unsupported_version": "RejectedFormatErrorClass::UnsupportedVersion",
}


ScenarioEntry = tuple[str, str, tuple[str, ...], tuple[str, ...]]


def _branches(value: Any, location: str) -> tuple[str, ...]:
    if (
        not isinstance(value, list)
        or any(not isinstance(branch, str) or not branch for branch in value)
        or value != sorted(value)
        or len(value) != len(set(value))
    ):
        raise ValueError(f"{location} must be a sorted unique string array")
    return tuple(value)


def load_entries(path: Path = INVENTORY) -> tuple[str, list[ScenarioEntry]]:
    raw = path.read_bytes()
    document: Any = json.loads(raw)
    if not isinstance(document, dict) or document.get("protocol_version") != "1.2.0":
        raise ValueError("expected the protocol 1.2.0 scenario inventory")
    if document.get("document_type") != "dao_scenario_inventory":
        raise ValueError("expected a DAO scenario inventory")
    scenarios = document.get("scenarios")
    if not isinstance(scenarios, list) or not scenarios:
        raise ValueError("expected a non-empty scenarios array")

    entries: list[ScenarioEntry] = []
    for index, scenario in enumerate(scenarios):
        if not isinstance(scenario, dict) or not isinstance(scenario.get("id"), str):
            raise ValueError(f"scenarios[{index}] has an invalid id")
        operation = scenario.get("operation")
        if not isinstance(operation, dict):
            raise ValueError(f"scenarios[{index}].operation is invalid")
        outcome = operation.get("expected_outcome")
        error_class = operation.get("error_class")
        if outcome == "success" and error_class is None:
            expectation = "ScenarioExpectation::Success"
        elif outcome == "expected_error" and error_class in ERROR_CLASSES:
            expectation = f"ScenarioExpectation::OpeningFailure({ERROR_CLASSES[error_class]})"
        else:
            raise ValueError(f"scenarios[{index}] has an unsupported outcome binding")
        required = _branches(
            scenario.get("required_branches"),
            f"scenarios[{index}].required_branches",
        )
        boundary = scenario.get("boundary")
        if boundary is None:
            forbidden: tuple[str, ...] = ()
        elif isinstance(boundary, dict):
            forbidden = _branches(
                boundary.get("forbidden_branches"),
                f"scenarios[{index}].boundary.forbidden_branches",
            )
        else:
            raise ValueError(f"scenarios[{index}].boundary is invalid")
        overlap = sorted(set(required) & set(forbidden))
        if overlap:
            raise ValueError(
                f"scenarios[{index}] cannot require and forbid branches {overlap}"
            )
        entries.append((scenario["id"], expectation, required, forbidden))

    identifiers = [identifier for identifier, *_ in entries]
    if identifiers != sorted(identifiers) or len(identifiers) != len(set(identifiers)):
        raise ValueError("scenario ids must be unique and sorted")
    return hashlib.sha256(raw).hexdigest(), entries


def render(path: Path = INVENTORY) -> str:
    digest, entries = load_entries(path)
    lines = [
        "// @generated by tools/generate_scenario_inventory.py; do not edit.",
        "#[cfg(test)]",
        f'pub(super) const INVENTORY_SHA256: &str = "{digest}";',
        "#[rustfmt::skip]",
        "const SCENARIOS: &[ScenarioDefinition] = &[",
    ]
    for identifier, expectation, required, forbidden in entries:
        required_rust = ", ".join(f'"{branch}"' for branch in required)
        forbidden_rust = ", ".join(f'"{branch}"' for branch in forbidden)
        lines.append(
            f'    ScenarioDefinition::new("{identifier}", {expectation}, '
            f'&[{required_rust}], &[{forbidden_rust}]),'
        )
    lines.extend([
        "];",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is stale")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} matches {INVENTORY.relative_to(ROOT)}")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
